<div class="travel-editor-form" aria-label="Tour media and attachments">
    @if(session('success'))<div class="alert alert-success mx-4 mt-3 mb-0" role="status">{{ session('success') }}</div>@endif
    @error('media')<div class="alert alert-danger mx-4 mt-3 mb-0" role="alert">{{ $message }}</div>@enderror
    <section class="travel-editor-section" aria-labelledby="tour-cover-heading">
        <div class="travel-editor-section-heading"><span>01</span><div><h4 id="tour-cover-heading">Cover image</h4><p>The primary image for search, social previews, and the tour page.</p></div></div>
        @php($cover = $tour->getFirstMedia('tour_cover'))
        @if($cover)<div class="travel-admin-media-item travel-tour-cover-preview"><img src="{{ $cover->hasGeneratedConversion('card') ? $cover->getUrl('card') : $cover->getUrl() }}" alt="{{ $cover->getCustomProperty('alt_text', '') }}"><p>{{ $cover->getCustomProperty('alt_text', '') }}</p><div class="travel-admin-media-actions"><button type="button" class="btn btn-sm btn-outline-secondary" wire:click="editImage({{ $cover->id }})">Edit text</button><button type="button" class="btn btn-sm btn-outline-danger" wire:click="removeCover" wire:confirm="Remove this tour cover?">Remove cover</button></div></div>@endif
        <form wire:submit="replaceCover" class="row g-3 mt-1" novalidate>
            <div class="col-md-5"><label class="form-label" for="tour-cover-upload">{{ $cover ? 'Replace cover' : 'Upload cover' }}</label><input id="tour-cover-upload" type="file" accept="image/jpeg,image/png,image/webp" class="form-control @error('coverUpload') is-invalid @enderror" wire:model="coverUpload">@error('coverUpload')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="tour-cover-alt">Alternative text</label><input id="tour-cover-alt" class="form-control @error('coverAltText') is-invalid @enderror" wire:model.blur="coverAltText" maxlength="180">@error('coverAltText')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-3"><label class="form-label" for="tour-cover-caption">Caption</label><input id="tour-cover-caption" class="form-control" wire:model.blur="coverCaption" maxlength="320"></div>
            @if($coverUpload && method_exists($coverUpload, 'temporaryUrl'))<div class="col-12"><figure class="travel-admin-upload-preview"><img src="{{ $coverUpload->temporaryUrl() }}" alt="{{ $coverAltText ?: 'Selected cover preview' }}"><figcaption>{{ $coverAltText }}</figcaption></figure></div>@endif
            <div class="col-12"><button type="submit" class="btn btn-primary" wire:loading.attr="disabled" wire:target="replaceCover,coverUpload">Save cover</button></div>
        </form>
    </section>
    <section class="travel-editor-section" aria-labelledby="tour-gallery-heading">
        @php($gallery = $tour->getMedia('tour_gallery'))
        <div class="travel-child-toolbar"><div><h4 id="tour-gallery-heading">Gallery</h4><p>{{ $gallery->count() }} / {{ config('travel-tours.media.tour_gallery_limit', 18) }} traveler-facing images in display order.</p></div><button type="button" class="btn btn-outline-secondary" wire:click="openGalleryDialog"><i class="ti ti-plus me-1" aria-hidden="true"></i>Add image</button></div>
        <div class="travel-admin-media-grid">
            @forelse($gallery as $image)<article class="travel-admin-media-item" wire:key="tour-gallery-{{ $image->id }}"><img src="{{ $image->hasGeneratedConversion('thumb') ? $image->getUrl('thumb') : $image->getUrl() }}" alt="{{ $image->getCustomProperty('alt_text', '') }}"><p>{{ $image->getCustomProperty('alt_text', '') }}</p><div class="travel-admin-media-actions"><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="editImage({{ $image->id }})" aria-label="Edit image text" title="Edit text"><i class="ti ti-pencil" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="moveGalleryImage({{ $image->id }}, 'up')" aria-label="Move image earlier" title="Move earlier"><i class="ti ti-arrow-left" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="moveGalleryImage({{ $image->id }}, 'down')" aria-label="Move image later" title="Move later"><i class="ti ti-arrow-right" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="removeGalleryImage({{ $image->id }})" wire:confirm="Remove this gallery image?" aria-label="Remove image" title="Remove image"><i class="ti ti-trash" aria-hidden="true"></i></button></div></article>@empty<div class="travel-child-empty">No gallery images yet.</div>@endforelse
        </div>
    </section>
    <section class="travel-editor-section" aria-labelledby="tour-attachments-heading">
        <div class="travel-editor-section-heading"><span>03</span><div><h4 id="tour-attachments-heading">Public attachments</h4><p>Traveler-facing PDFs or Word files. Do not upload private traveler documents here.</p></div></div>
        <div class="travel-child-list">
            @forelse($tour->getMedia('tour_documents') as $document)<div class="travel-child-entry" wire:key="tour-document-{{ $document->id }}"><div class="travel-child-entry__head"><div><strong>{{ $document->getCustomProperty('title', $document->name) }}</strong><p>{{ $document->getCustomProperty('description', '') }} · {{ strtoupper($document->extension) }}</p></div><div class="travel-child-actions"><a class="btn btn-icon btn-sm btn-outline-secondary" href="{{ $document->getUrl() }}" target="_blank" rel="noopener noreferrer" aria-label="Open attachment" title="Open attachment"><i class="ti ti-external-link" aria-hidden="true"></i></a><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="removeDocument({{ $document->id }})" wire:confirm="Remove this public attachment?" aria-label="Remove attachment" title="Remove attachment"><i class="ti ti-trash" aria-hidden="true"></i></button></div></div></div>@empty<div class="travel-child-empty">No public attachments yet.</div>@endforelse
        </div>
        <form wire:submit="addDocument" class="row g-3 mt-2" novalidate>
            <div class="col-md-5"><label class="form-label" for="tour-document-upload">Add attachment</label><input id="tour-document-upload" type="file" accept=".pdf,.doc,.docx" class="form-control @error('documentUpload') is-invalid @enderror" wire:model="documentUpload">@error('documentUpload')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="tour-document-title">Public title</label><input id="tour-document-title" class="form-control @error('documentTitle') is-invalid @enderror" wire:model.blur="documentTitle" maxlength="180">@error('documentTitle')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-3"><label class="form-label" for="tour-document-description">Description</label><input id="tour-document-description" class="form-control" wire:model.blur="documentDescription" maxlength="500"></div>
            <div class="col-12"><button type="submit" class="btn btn-outline-secondary" wire:loading.attr="disabled" wire:target="addDocument,documentUpload">Add attachment</button></div>
        </form>
    </section>
    @if($editingImageId !== null)<div class="modal fade show d-block travel-child-modal" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="tour-image-text-heading" wire:keydown.escape.window="closeImageMetadata"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" role="document"><form class="modal-content" wire:submit="saveImageMetadata" novalidate><div class="modal-header"><h3 id="tour-image-text-heading" class="modal-title fs-18">Edit image text</h3><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="closeImageMetadata" aria-label="Close image text"><i class="ti ti-x" aria-hidden="true"></i></button></div><div class="modal-body row g-3"><div class="col-12"><label class="form-label" for="tour-image-alt">Alternative text</label><input id="tour-image-alt" class="form-control @error('mediaAltText') is-invalid @enderror" wire:model.blur="mediaAltText" maxlength="180" autofocus>@error('mediaAltText')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="tour-image-caption">Caption</label><input id="tour-image-caption" class="form-control" wire:model.blur="mediaCaption" maxlength="320"></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeImageMetadata">Cancel</button><button type="submit" class="btn btn-primary">Save text</button></div></form></div></div><div class="modal-backdrop fade show"></div>@endif
    @if($galleryDialog)<div class="modal fade show d-block travel-child-modal" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="tour-gallery-add-heading" wire:keydown.escape.window="closeGalleryDialog"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" role="document"><form class="modal-content" wire:submit="addGalleryImage" novalidate><div class="modal-header"><h3 id="tour-gallery-add-heading" class="modal-title fs-18">Add gallery image</h3><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="closeGalleryDialog" aria-label="Close gallery upload"><i class="ti ti-x" aria-hidden="true"></i></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label" for="tour-gallery-upload">Image</label><input id="tour-gallery-upload" type="file" accept="image/jpeg,image/png,image/webp" class="form-control @error('galleryUpload') is-invalid @enderror" wire:model="galleryUpload" autofocus>@error('galleryUpload')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@if($galleryUpload && method_exists($galleryUpload, 'temporaryUrl'))<div class="col-12"><figure class="travel-admin-upload-preview"><img src="{{ $galleryUpload->temporaryUrl() }}" alt="{{ $galleryAltText ?: 'Selected gallery preview' }}"><figcaption>{{ $galleryAltText }}</figcaption></figure></div>@endif<div class="col-12"><label class="form-label" for="tour-gallery-alt">Alternative text</label><input id="tour-gallery-alt" class="form-control @error('galleryAltText') is-invalid @enderror" wire:model.blur="galleryAltText" maxlength="180">@error('galleryAltText')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="tour-gallery-caption">Caption</label><input id="tour-gallery-caption" class="form-control" wire:model.blur="galleryCaption" maxlength="320"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeGalleryDialog">Cancel</button><button type="submit" class="btn btn-primary" wire:loading.attr="disabled" wire:target="addGalleryImage,galleryUpload">Add image</button></div></form></div></div><div class="modal-backdrop fade show"></div>@endif
</div>
