<div class="travel-editor-form" aria-label="Tour experience editor">
    @if(session('success'))<div class="alert alert-success mx-4 mt-3 mb-0" role="status">{{ session('success') }}</div>@endif
    @error('management')<div class="alert alert-danger mx-4 mt-3 mb-0" role="alert">{{ $message }}</div>@enderror
    <section class="travel-editor-section" aria-labelledby="experience-content-heading">
        <div class="travel-child-toolbar"><div><h4 id="experience-content-heading">Highlights and essentials</h4><p>Traveler-facing inclusions, exclusions, requirements, and packing notes.</p></div><button type="button" class="btn btn-primary" wire:click="open('item')"><i class="ti ti-plus me-1" aria-hidden="true"></i>Add item</button></div>
        <div class="travel-child-list">
            @forelse($tour->contentItems as $item)
                <div class="travel-child-entry" wire:key="experience-item-{{ $item->id }}"><div class="travel-child-entry__head"><div><span class="travel-status travel-status--muted">{{ $item->type->label() }}</span><strong class="mt-2">{{ $item->title ?: $item->content }}</strong>@if($item->title)<p>{{ $item->content }}</p>@endif</div><div class="travel-child-actions"><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="move('item', {{ $item->id }}, 'up')" aria-label="Move item earlier" title="Move earlier"><i class="ti ti-arrow-up" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="move('item', {{ $item->id }}, 'down')" aria-label="Move item later" title="Move later"><i class="ti ti-arrow-down" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="edit('item', {{ $item->id }})" aria-label="Edit item" title="Edit item"><i class="ti ti-edit" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="remove('item', {{ $item->id }})" wire:confirm="Remove this item?" aria-label="Remove item" title="Remove item"><i class="ti ti-trash" aria-hidden="true"></i></button></div></div></div>
            @empty<div class="travel-child-empty">No experience items yet.</div>@endforelse
        </div>
    </section>
    <section class="travel-editor-section" aria-labelledby="experience-faq-heading">
        <div class="travel-child-toolbar"><div><h4 id="experience-faq-heading">Frequently asked questions</h4><p>Answers shown on the public tour page when active.</p></div><button type="button" class="btn btn-outline-secondary" wire:click="open('faq')"><i class="ti ti-plus me-1" aria-hidden="true"></i>Add FAQ</button></div>
        <div class="travel-child-list">
            @forelse($tour->faqs as $faq)
                <div class="travel-child-entry" wire:key="experience-faq-{{ $faq->id }}"><div class="travel-child-entry__head"><div><strong>{{ $faq->question }}</strong><p>{{ $faq->answer }}</p>@unless($faq->is_active)<span class="travel-status travel-status--muted">Hidden</span>@endunless</div><div class="travel-child-actions"><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="move('faq', {{ $faq->id }}, 'up')" aria-label="Move FAQ earlier" title="Move earlier"><i class="ti ti-arrow-up" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="move('faq', {{ $faq->id }}, 'down')" aria-label="Move FAQ later" title="Move later"><i class="ti ti-arrow-down" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="edit('faq', {{ $faq->id }})" aria-label="Edit FAQ" title="Edit FAQ"><i class="ti ti-edit" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="remove('faq', {{ $faq->id }})" wire:confirm="Remove this FAQ?" aria-label="Remove FAQ" title="Remove FAQ"><i class="ti ti-trash" aria-hidden="true"></i></button></div></div></div>
            @empty<div class="travel-child-empty">No FAQs yet.</div>@endforelse
        </div>
    </section>
    <section class="travel-editor-section" aria-labelledby="experience-extra-heading">
        <div class="travel-child-toolbar"><div><h4 id="experience-extra-heading">Optional extras</h4><p>Add-ons offered alongside the tour price.</p></div><button type="button" class="btn btn-outline-secondary" wire:click="open('extra')"><i class="ti ti-plus me-1" aria-hidden="true"></i>Add extra</button></div>
        <div class="travel-child-list">
            @forelse($tour->extras as $extra)
                <div class="travel-child-entry" wire:key="experience-extra-{{ $extra->id }}"><div class="travel-child-entry__head"><div><strong>{{ $extra->name }}</strong><p>{{ $extra->code }} | {{ \App\Modules\TravelTours\Support\MoneyFormatter::format($extra->amount_minor, $extra->currency) }} / {{ str_replace('_', ' ', $extra->pricing_unit) }}</p>@if($extra->description)<p>{{ $extra->description }}</p>@endif @unless($extra->is_active && $extra->is_public)<span class="travel-status travel-status--muted">{{ $extra->is_active ? 'Private' : 'Inactive' }}</span>@endunless</div><div class="travel-child-actions"><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="move('extra', {{ $extra->id }}, 'up')" aria-label="Move extra earlier" title="Move earlier"><i class="ti ti-arrow-up" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="move('extra', {{ $extra->id }}, 'down')" aria-label="Move extra later" title="Move later"><i class="ti ti-arrow-down" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="edit('extra', {{ $extra->id }})" aria-label="Edit extra" title="Edit extra"><i class="ti ti-edit" aria-hidden="true"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="remove('extra', {{ $extra->id }})" wire:confirm="Archive this extra?" aria-label="Archive extra" title="Archive extra"><i class="ti ti-archive" aria-hidden="true"></i></button></div></div></div>
            @empty<div class="travel-child-empty">No extras yet.</div>@endforelse
        </div>
    </section>

    @if($editor !== '')
        @php($editorLabel = $editor === 'faq' ? 'FAQ' : ($editor === 'extra' ? 'optional extra' : 'experience item'))
        <div class="modal fade show d-block travel-child-modal" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="experience-edit-heading" wire:keydown.escape.window="cancel">
            <div class="modal-dialog {{ $editor === 'extra' ? 'modal-xl' : 'modal-lg' }} modal-dialog-centered modal-dialog-scrollable" role="document">
                <form class="modal-content" wire:submit="save" novalidate>
                    <div class="modal-header"><div><h3 id="experience-edit-heading" class="modal-title fs-18">{{ $editingId ? 'Edit' : 'Add' }} {{ $editorLabel }}</h3><p class="aureon-muted mb-0 fs-12">Update the traveler-facing experience without leaving this tour.</p></div><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="cancel" aria-label="Close {{ $editorLabel }} form"><i class="ti ti-x" aria-hidden="true"></i></button></div>
                    <div class="modal-body">
                        @error('management')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror
                @if($editor === 'item')
                    <div class="row g-3"><div class="col-md-4"><label class="form-label" for="experience-item-type">Type</label><select id="experience-item-type" class="form-select" wire:model="itemForm.type" autofocus>@foreach(\App\Modules\TravelTours\Catalog\Enums\ContentItemType::cases() as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</select></div><div class="col-md-8"><label class="form-label" for="experience-item-title">Heading</label><input id="experience-item-title" class="form-control" wire:model.blur="itemForm.title" maxlength="180"></div><div class="col-12"><label class="form-label" for="experience-item-content">Content</label><textarea id="experience-item-content" class="form-control @error('itemForm.content') is-invalid @enderror" rows="3" wire:model.blur="itemForm.content" required></textarea>@error('itemForm.content')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
                @elseif($editor === 'faq')
                    <div class="row g-3"><div class="col-12"><label class="form-label" for="experience-faq-question">Question</label><input id="experience-faq-question" class="form-control @error('faqForm.question') is-invalid @enderror" wire:model.blur="faqForm.question" maxlength="320" required autofocus>@error('faqForm.question')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="experience-faq-answer">Answer</label><textarea id="experience-faq-answer" class="form-control @error('faqForm.answer') is-invalid @enderror" rows="4" wire:model.blur="faqForm.answer" required></textarea>@error('faqForm.answer')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><div class="form-check form-switch"><input id="experience-faq-active" type="checkbox" class="form-check-input" wire:model="faqForm.isActive"><label class="form-check-label" for="experience-faq-active">Show on public tour page</label></div></div></div>
                @else
                    <div class="row g-3">
                        <div class="col-md-4"><label class="form-label" for="experience-extra-code">Code</label><input id="experience-extra-code" class="form-control @error('extraForm.code') is-invalid @enderror" wire:model.blur="extraForm.code" maxlength="40" required autofocus>@error('extraForm.code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-8"><label class="form-label" for="experience-extra-name">Name</label><input id="experience-extra-name" class="form-control @error('extraForm.name') is-invalid @enderror" wire:model.blur="extraForm.name" maxlength="180" required>@error('extraForm.name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-12"><label class="form-label" for="experience-extra-description">Description</label><textarea id="experience-extra-description" class="form-control" rows="3" wire:model.blur="extraForm.description"></textarea></div>
                        <div class="col-6 col-md-3"><label class="form-label" for="experience-extra-amount">Amount</label><input id="experience-extra-amount" inputmode="decimal" class="form-control @error('extraForm.amount') is-invalid @enderror" wire:model.blur="extraForm.amount" required>@error('extraForm.amount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-md-3"><label class="form-label" for="experience-extra-currency">Currency</label><input id="experience-extra-currency" class="form-control @error('extraForm.currency') is-invalid @enderror" wire:model.blur="extraForm.currency" maxlength="3" required>@error('extraForm.currency')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-6"><label class="form-label" for="experience-extra-unit">Pricing unit</label><select id="experience-extra-unit" class="form-select" wire:model="extraForm.pricingUnit"><option value="per_person">Per participant</option><option value="per_booking">Per booking</option></select></div>
                        <div class="col-6 col-md-3"><label class="form-label" for="experience-extra-minimum">Minimum quantity</label><input id="experience-extra-minimum" type="number" min="0" max="1000" class="form-control" wire:model="extraForm.minimumQuantity">@error('extraForm.minimumQuantity')<div class="text-danger fs-12">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-md-3"><label class="form-label" for="experience-extra-maximum">Maximum quantity</label><input id="experience-extra-maximum" type="number" min="1" max="1000" class="form-control" wire:model="extraForm.maximumQuantity">@error('extraForm.maximumQuantity')<div class="text-danger fs-12">{{ $message }}</div>@enderror</div>
                        <div class="col-md-6"><span class="form-label d-block">Participant types</span>@foreach(\App\Modules\TravelTours\Bookings\Enums\ParticipantType::cases() as $type)<div class="form-check form-check-inline"><input id="experience-extra-type-{{ $type->value }}" type="checkbox" class="form-check-input" value="{{ $type->value }}" wire:model="extraForm.participantTypes"><label class="form-check-label" for="experience-extra-type-{{ $type->value }}">{{ $type->label() }}</label></div>@endforeach</div>
                        <div class="col-md-6 d-flex align-items-end gap-4"><div class="form-check form-switch"><input id="experience-extra-active" type="checkbox" class="form-check-input" wire:model="extraForm.isActive"><label class="form-check-label" for="experience-extra-active">Active</label></div><div class="form-check form-switch"><input id="experience-extra-public" type="checkbox" class="form-check-input" wire:model="extraForm.isPublic"><label class="form-check-label" for="experience-extra-public">Public</label></div></div>
                    </div>
                @endif
                    </div>
                    <div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="cancel">Cancel</button><button type="submit" class="btn btn-primary" wire:loading.attr="disabled" wire:target="save">Save {{ $editorLabel }}</button></div>
                </form>
            </div>
        </div>
        <div class="modal-backdrop fade show"></div>
    @endif
</div>
