<div id="roles-and-permissions-manager">
    @if (session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    @error('management')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror

    @php
        $roleStats = [
            ['label' => 'Access roles', 'value' => $this->statistics['roles'], 'icon' => 'ti-shield', 'color' => 'var(--aureon-primary)'],
            ['label' => 'Capabilities', 'value' => $this->statistics['permissions'], 'icon' => 'ti-key', 'color' => 'var(--aureon-secondary)'],
            ['label' => 'Role assignments', 'value' => $this->statistics['assignments'], 'icon' => 'ti-user-shield', 'color' => '#9a6d1f'],
            ['label' => 'Custom roles', 'value' => $this->statistics['custom'], 'icon' => 'ti-shield-plus', 'color' => '#596274'],
        ];
    @endphp
    <section class="row" aria-label="Access-control statistics">@foreach ($roleStats as $stat)<div class="col-xl-3 col-sm-6 d-flex"><article class="card aureon-stat mb-4" style="--stat-color: {{ $stat['color'] }}"><div class="card-body d-flex align-items-center gap-3"><span class="aureon-stat__icon"><i class="ti {{ $stat['icon'] }}"></i></span><div><h3>{{ number_format($stat['value']) }}</h3><p>{{ $stat['label'] }}</p></div></div></article></div>@endforeach</section>

    <section class="card aureon-panel aureon-table-panel mb-4" aria-labelledby="role-list-title">
        <div class="card-header d-flex align-items-center justify-content-between gap-3"><div><h3 id="role-list-title" class="card-title mb-1">Role catalogue</h3><p class="aureon-muted fs-12 mb-0">Permissions are capabilities defined by application code</p></div>@can(\App\Support\CmsPermission::MANAGE_ROLES_AND_PERMISSIONS)<button type="button" class="btn btn-primary" wire:click="openCreate"><i class="ti ti-shield-plus me-2"></i>Add role</button>@endcan</div>
        <div class="card-body border-bottom"><div class="row"><div class="col-lg-5"><label for="role-search" class="form-label">Search roles</label><div class="input-group"><span class="input-group-text"><i class="ti ti-search"></i></span><input id="role-search" type="search" class="form-control" wire:model.live.debounce.300ms="search" placeholder="Role name"></div></div></div></div>
        <div class="table-responsive"><table class="table table-hover align-middle mb-0 aureon-role-table"><thead><tr><th scope="col">Role</th><th scope="col">Type</th><th scope="col">Users</th><th scope="col">Permissions</th><th scope="col" class="text-end"><span class="visually-hidden">Actions</span></th></tr></thead><tbody>
            @forelse ($this->roles as $role)
                @php($baseRole = in_array($role->name, \App\Enums\UserType::values(), true))
                <tr wire:key="role-{{ $role->id }}"><td><span class="d-block fw-semibold">{{ str($role->name)->replace('-', ' ')->title() }}</span><code class="aureon-event-name">{{ $role->name }}</code></td><td><span class="badge aureon-role-badge {{ $baseRole ? '' : 'aureon-role-badge--neutral' }}">{{ $baseRole ? 'Base role' : 'Custom role' }}</span></td><td>{{ number_format($role->users_count) }}</td><td><span class="d-block fw-semibold">{{ $role->permissions->count() }} capabilities</span><small class="aureon-muted">{{ $role->permissions->take(3)->pluck('name')->map(fn ($name) => str($name)->replace('_', ' '))->implode(', ') ?: 'No permissions assigned' }}@if ($role->permissions->count() > 3) +{{ $role->permissions->count() - 3 }} more @endif</small></td><td class="text-end text-nowrap">
                    @can(\App\Support\CmsPermission::MANAGE_ROLES_AND_PERMISSIONS)
                        @if ($role->name !== \App\Enums\UserType::SystemAdministrator->value)<button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openEdit({{ $role->id }})" title="Edit role" aria-label="Edit {{ $role->name }} role"><i class="ti ti-edit"></i></button>@else<span class="badge aureon-role-badge aureon-role-badge--neutral"><i class="ti ti-lock me-1"></i>Locked</span>@endif
                        @if (! $baseRole)<button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="confirmDelete({{ $role->id }})" title="Delete role" aria-label="Delete {{ $role->name }} role"><i class="ti ti-trash"></i></button>@endif
                    @endcan
                </td></tr>
            @empty<tr><td colspan="5" class="text-center py-5"><span class="aureon-empty-state__icon"><i class="ti ti-shield-off"></i></span><h4 class="fs-16 mb-1">No roles found</h4><p class="aureon-muted mb-0">Adjust the search or create a custom role.</p></td></tr>@endforelse
        </tbody></table></div>
    </section>

    <section class="card aureon-panel mb-4" aria-labelledby="permission-catalogue-title"><div class="card-header"><h3 id="permission-catalogue-title" class="card-title mb-1">Permission catalogue</h3><p class="aureon-muted fs-12 mb-0">Stable capability identifiers available for role composition</p></div><div class="card-body"><div class="row g-4">@foreach ($this->groupedPermissions as $group => $permissions)<div class="col-xl-4 col-md-6"><h4 class="fs-14 mb-3">{{ $group }}</h4><div class="aureon-permission-list">@foreach ($permissions as $name => $metadata)<div><span class="d-block fw-semibold fs-13">{{ $metadata['label'] }}</span><code>{{ $name }}</code><p class="aureon-muted fs-12 mb-0">{{ $metadata['description'] }}</p></div>@endforeach</div></div>@endforeach</div></div></section>

    @if ($dialog === 'form')
        @php($editing = $selectedRoleId !== null)
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="role-form-title" wire:keydown.escape.window="closeDialog"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable" role="document"><form class="modal-content" wire:submit="save">
            <div class="modal-header"><div><h3 id="role-form-title" class="modal-title fs-18">{{ $editing ? 'Edit access role' : 'Create access role' }}</h3><p class="aureon-muted fs-12 mb-0">Bundle application capabilities for assignment to users</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close role form"></button></div>
            <div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror<div class="row g-4"><div class="col-lg-4"><label for="role-name" class="form-label">Role identifier <span class="text-danger">*</span></label><input id="role-name" type="text" class="form-control @error('form.name') is-invalid @enderror" wire:model.live.blur="form.name" @disabled($editing && in_array($form->name, \App\Enums\UserType::values(), true)) placeholder="communications-manager">@error('form.name')<div class="invalid-feedback">{{ $message }}</div>@enderror<p class="aureon-muted fs-12 mt-2">Lowercase letters, numbers, and single hyphens. Base identifiers are fixed.</p><div class="aureon-access-note"><i class="ti ti-info-circle"></i><p>Assign permissions to roles, then roles to users. Direct user permissions are intentionally excluded.</p></div></div>
                <div class="col-lg-8"><div class="aureon-permission-groups">@foreach ($this->groupedPermissions as $group => $permissions)@php($groupNames = array_keys($permissions)) @php($allSelected = count(array_intersect($groupNames, $form->permissions)) === count($groupNames))<section><div class="d-flex align-items-center justify-content-between gap-3 mb-3"><h4 class="fs-15 mb-0">{{ $group }}</h4><button type="button" class="btn btn-sm btn-link px-0" wire:click="togglePermissionGroup('{{ $group }}', {{ $allSelected ? 'false' : 'true' }})">{{ $allSelected ? 'Clear group' : 'Select group' }}</button></div><div class="row g-2">@foreach ($permissions as $name => $metadata)<div class="col-md-6"><label class="aureon-permission-option" for="permission-{{ md5($name) }}"><input id="permission-{{ md5($name) }}" type="checkbox" class="form-check-input" value="{{ $name }}" wire:model="form.permissions"><span><strong>{{ $metadata['label'] }}</strong><small>{{ $metadata['description'] }}</small></span></label></div>@endforeach</div></section>@endforeach</div>@error('form.permissions.*')<div class="text-danger fs-12 mt-2">{{ $message }}</div>@enderror</div></div></div>
            <div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary" wire:loading.attr="disabled" wire:target="save"><i class="ti ti-device-floppy me-2"></i><span wire:loading.remove wire:target="save">{{ $editing ? 'Save role' : 'Create role' }}</span><span wire:loading wire:target="save">Saving...</span></button></div>
        </form></div></div><button type="button" class="modal-backdrop fade show border-0 w-100" wire:click="closeDialog" aria-label="Close role form"></button>
    @endif

    @if ($dialog === 'delete' && $this->selectedRole)
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="delete-role-title" wire:keydown.escape.window="closeDialog"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header"><h3 id="delete-role-title" class="modal-title fs-18">Delete access role</h3><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close delete confirmation"></button></div><div class="modal-body"><p class="mb-2">Delete <strong>{{ str($this->selectedRole->name)->replace('-', ' ')->title() }}</strong>?</p><p class="aureon-muted mb-0">Only unassigned custom roles can be removed. The permission catalogue is not changed.</p></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="button" class="btn btn-danger" wire:click="delete" wire:loading.attr="disabled" wire:target="delete"><i class="ti ti-trash me-2"></i>Delete role</button></div></div></div></div><button type="button" class="modal-backdrop fade show border-0 w-100" wire:click="closeDialog" aria-label="Close delete confirmation"></button>
    @endif
</div>
