<div>
    <section class="pb-stay-search-band" id="stay-search" aria-labelledby="stay-search-title"><div class="container-xxl"><div class="pb-stay-search-heading"><div><p class="pb-storefront-eyebrow">Availability search</p><h2 id="stay-search-title">Plan your stay</h2></div><p>Dates and times are interpreted in each property's local timezone.</p></div><form class="pb-stay-search" wire:submit="search" novalidate>
        <div class="pb-stay-field"><label for="search-arrival">Arrival</label><input id="search-arrival" type="date" wire:model="form.arrivalDate" min="{{ now()->toDateString() }}" required>@error('form.arrivalDate')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field"><label for="search-arrival-time">Time</label><input id="search-arrival-time" type="time" wire:model="form.arrivalTime" required>@error('form.arrivalTime')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field"><label for="search-departure">Departure</label><input id="search-departure" type="date" wire:model="form.departureDate" min="{{ $form->arrivalDate }}" required>@error('form.departureDate')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field"><label for="search-departure-time">Time</label><input id="search-departure-time" type="time" wire:model="form.departureTime" required>@error('form.departureTime')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field"><label for="search-adults">Adults</label><input id="search-adults" type="number" wire:model="form.adults" min="1" max="20" inputmode="numeric" required>@error('form.adults')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field"><label for="search-children">Children</label><input id="search-children" type="number" wire:model="form.children" min="0" max="20" inputmode="numeric">@error('form.children')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field"><label for="search-infants">Infants</label><input id="search-infants" type="number" wire:model="form.infants" min="0" max="10" inputmode="numeric">@error('form.infants')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field"><label for="search-category">Stay type</label><select id="search-category" wire:model="form.category"><option value="">All types</option>@foreach($this->categories as $category)<option value="{{ $category->slug }}">{{ $category->name }}</option>@endforeach</select>@error('form.category')<small>{{ $message }}</small>@enderror</div>
        <div class="pb-stay-field pb-stay-field--location"><label for="search-location">Location</label><input id="search-location" type="search" wire:model="form.location" maxlength="100" placeholder="City or region">@error('form.location')<small>{{ $message }}</small>@enderror</div>
        <button class="pb-storefront-button" type="submit" wire:loading.attr="disabled" wire:target="search"><i data-lucide="search" wire:loading.remove wire:target="search" aria-hidden="true"></i><span class="pb-storefront-spinner" wire:loading wire:target="search" aria-hidden="true"></span><span>Search</span></button>
    </form></div></section>

    <section class="pb-stay-results" aria-labelledby="stay-results-title"><div class="container-xxl">@error('availability')<div class="pb-storefront-notice pb-storefront-notice--error" role="alert">{{ $message }}</div>@enderror<div class="pb-stay-results__heading"><div><p class="pb-storefront-eyebrow">Available now</p><h2 id="stay-results-title">{{ number_format($results->count()) }} {{ \Illuminate\Support\Str::plural('property', $results->count()) }}</h2></div><button class="pb-storefront-text-button" type="button" wire:click="clearFilters"><i data-lucide="rotate-ccw" aria-hidden="true"></i>Reset search</button></div>
        <div class="pb-stay-result-grid">@forelse($results as $result)@php($cover = $result->property->getFirstMedia('property_cover'))<article class="pb-stay-card" wire:key="property-result-{{ $result->property->ulid }}"><a class="pb-stay-card__image" href="{{ route('property-booking.storefront.properties.show', ['property' => $result->property->slug, ...$this->queryParameters()]) }}">@if($cover)<img src="{{ $cover->getUrl('card') }}" alt="{{ $cover->getCustomProperty('alt_text', $result->property->name) }}" width="720" height="540" loading="lazy">@else<span><i data-lucide="building-2" aria-hidden="true"></i></span>@endif @if($result->property->is_featured)<strong>Featured</strong>@endif</a><div class="pb-stay-card__body"><div class="pb-stay-card__location"><span>{{ $result->property->category?->name }}</span><span><i data-lucide="map-pin" aria-hidden="true"></i>{{ collect([$result->property->city, $result->property->region])->filter()->implode(', ') }}</span></div><h3><a href="{{ route('property-booking.storefront.properties.show', ['property' => $result->property->slug, ...$this->queryParameters()]) }}">{{ $result->property->name }}</a></h3><p>{{ $result->property->short_description }}</p><div class="pb-stay-card__meta"><span><i data-lucide="bed-double" aria-hidden="true"></i>{{ count($result->options) }} rate {{ \Illuminate\Support\Str::plural('option', count($result->options)) }}</span><span><i data-lucide="door-open" aria-hidden="true"></i>{{ $result->availableUnitCount() }} available</span></div><div class="pb-stay-card__footer"><div><small>Stay total from</small><strong>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($result->minimumTotalMinor(), $result->property->currency) }}</strong></div><a class="pb-storefront-icon-button" href="{{ route('property-booking.storefront.properties.show', ['property' => $result->property->slug, ...$this->queryParameters()]) }}" aria-label="View {{ $result->property->name }}" title="View property"><i data-lucide="arrow-up-right" aria-hidden="true"></i></a></div></div></article>@empty<div class="pb-storefront-empty"><i data-lucide="calendar-x-2" aria-hidden="true"></i><h3>No current match</h3><p>Try another date, time, occupancy, or location. Nothing has been reserved by this search.</p></div>@endforelse</div>
    </div></section>
</div>
