<div id="commerce-inventory-manager">
    @php($stats = [
        ['label' => 'Stock records', 'value' => $this->statistics['products'], 'icon' => 'ti-package', 'color' => 'var(--aureon-primary)'],
        ['label' => 'Units on hand', 'value' => $this->statistics['units'], 'icon' => 'ti-stack-2', 'color' => 'var(--aureon-secondary)'],
        ['label' => 'Low stock', 'value' => $this->statistics['low'], 'icon' => 'ti-alert-triangle', 'color' => '#d39e00'],
        ['label' => 'Out of stock', 'value' => $this->statistics['out'], 'icon' => 'ti-package-off', 'color' => '#dc3545'],
    ])

    <section class="row" aria-label="Inventory statistics">
        @foreach ($stats as $stat)<div class="col-xl-3 col-sm-6 d-flex"><article class="card aureon-stat mb-4" style="--stat-color: {{ $stat['color'] }}"><div class="card-body d-flex align-items-center gap-3"><span class="aureon-stat__icon"><i class="ti {{ $stat['icon'] }}"></i></span><div><h3>{{ number_format($stat['value']) }}</h3><p>{{ $stat['label'] }}</p></div></div></article></div>@endforeach
    </section>

    @if (session('success'))<div class="alert alert-success alert-dismissible fade show" role="status">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>@endif
    @error('management')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror

    <section class="card aureon-panel mb-4" aria-labelledby="inventory-filters-title">
        <div class="card-body"><div class="row g-3 align-items-end">
            <div class="col-xl-6 col-md-7"><label id="inventory-filters-title" for="inventory-search" class="form-label">Search inventory</label><div class="input-group"><span class="input-group-text"><i class="ti ti-search"></i></span><input id="inventory-search" type="search" class="form-control" wire:model.live.debounce.350ms="search" placeholder="Product name, SKU, or barcode"></div></div>
            <div class="col-xl-3 col-md-5"><label for="stock-state-filter" class="form-label">Stock state</label><select id="stock-state-filter" class="form-select" wire:model.live="stockFilter"><option value="">All stock</option><option value="healthy">Healthy</option><option value="low">Low stock</option><option value="out">Out of stock</option><option value="untracked">Not tracked</option></select></div>
            <div class="col-xl-2"><label for="inventory-per-page" class="form-label">Rows</label><select id="inventory-per-page" class="form-select" wire:model.live="perPage">@foreach ([10, 15, 25, 50] as $size)<option value="{{ $size }}">{{ $size }} per page</option>@endforeach</select></div>
            <div class="col-xl-1"><button type="button" class="btn btn-outline-secondary btn-icon w-100" wire:click="clearFilters" title="Clear filters" aria-label="Clear inventory filters"><i class="ti ti-filter-off"></i></button></div>
        </div></div>
    </section>

    <section class="card aureon-panel aureon-table-panel mb-4" aria-labelledby="stock-table-title">
        <div class="card-header d-flex align-items-center justify-content-between gap-3"><div><h3 id="stock-table-title" class="card-title mb-1">Current stock</h3><p class="aureon-muted fs-12 mb-0">{{ number_format($this->stocks->total()) }} matching projections</p></div><div class="d-flex align-items-center gap-2"><span class="aureon-activity-loading position-static" wire:loading.delay wire:target="search, stockFilter, perPage, stockPage" aria-live="polite"><span class="spinner-border spinner-border-sm"></span><span>Updating</span></span><button type="button" class="btn btn-outline-secondary btn-sm text-nowrap" wire:click="exportStockLevelsPdf" wire:loading.attr="disabled" wire:target="exportStockLevelsPdf" title="Export the filtered stock levels as PDF"><span wire:loading.remove wire:target="exportStockLevelsPdf"><i class="ti ti-file-type-pdf me-1"></i>Export PDF</span><span wire:loading wire:target="exportStockLevelsPdf"><span class="spinner-border spinner-border-sm me-1" aria-hidden="true"></span>Preparing</span></button></div></div>
        <div class="table-responsive"><table class="table table-hover align-middle mb-0 aureon-commerce-table"><thead><tr><th scope="col">Product</th><th scope="col">On hand</th><th scope="col">Low threshold</th><th scope="col">Tracking</th><th scope="col">Updated</th><th scope="col" class="text-end"><span class="visually-hidden">Actions</span></th></tr></thead><tbody>
            @forelse ($this->stocks as $stock)
                @php($state = $stock->on_hand <= 0 ? 'out' : ($stock->isLow() ? 'low' : 'healthy'))
                <tr wire:key="stock-{{ $stock->id }}"><td><span class="d-block fw-semibold">{{ $stock->product->name }}</span><code class="aureon-event-name">{{ $stock->product->sku }}</code></td><td><span class="d-block fw-semibold">{{ number_format($stock->on_hand) }}</span><small class="aureon-muted">{{ \Illuminate\Support\Str::plural($stock->product->unit_label, $stock->on_hand) }}</small></td><td>{{ number_format($stock->low_stock_threshold) }}</td><td>@if (! $stock->product->track_stock)<span class="badge aureon-commerce-badge aureon-commerce-badge--neutral">Not tracked</span>@else<span class="badge aureon-stock-badge aureon-stock-badge--{{ $state }}">{{ match ($state) {'out' => 'Out of stock', 'low' => 'Low stock', default => 'Healthy'} }}</span>@endif</td><td><span class="d-block">{{ $stock->updated_at?->format('d M Y') ?? 'Never' }}</span><small class="aureon-muted">{{ $stock->updated_at?->format('H:i') }}</small></td><td class="text-end">@can(\App\Modules\Commerce\Support\CommercePermission::MANAGE_INVENTORY)<button type="button" class="btn btn-sm btn-primary" wire:click="openAdjustment({{ $stock->id }})" @disabled(! $stock->product->track_stock)><i class="ti ti-adjustments-horizontal me-2"></i>Adjust</button>@endcan</td></tr>
            @empty
                <tr><td colspan="6" class="text-center py-5"><span class="aureon-empty-state__icon"><i class="ti ti-building-warehouse"></i></span><h4 class="fs-16 mb-1">No stock records found</h4><p class="aureon-muted mb-0">Adjust the filters or create products in the catalogue.</p></td></tr>
            @endforelse
        </tbody></table></div>
        @if ($this->stocks->hasPages())<div class="card-footer">{{ $this->stocks->onEachSide(1)->links() }}</div>@endif
    </section>

    <section class="card aureon-panel aureon-table-panel mb-4" aria-labelledby="movement-table-title">
        <div class="card-header d-flex align-items-end justify-content-between gap-3"><div><h3 id="movement-table-title" class="card-title mb-1">Movement history</h3><p class="aureon-muted fs-12 mb-0">Append-only inventory ledger</p></div><div class="d-flex align-items-center gap-2"><button type="button" class="btn btn-outline-secondary btn-sm text-nowrap" wire:click="exportMovementsPdf" wire:loading.attr="disabled" wire:target="exportMovementsPdf" title="Export the filtered movement history as PDF"><span wire:loading.remove wire:target="exportMovementsPdf"><i class="ti ti-file-type-pdf me-1"></i>Export PDF</span><span wire:loading wire:target="exportMovementsPdf"><span class="spinner-border spinner-border-sm me-1" aria-hidden="true"></span>Preparing</span></button><div><label for="movement-type-filter" class="visually-hidden">Movement type</label><select id="movement-type-filter" class="form-select form-select-sm" wire:model.live="movementTypeFilter"><option value="">All movement types</option>@foreach ($this->movementTypes as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</select></div></div></div>
        <div class="table-responsive"><table class="table table-hover align-middle mb-0 aureon-movement-table"><thead><tr><th scope="col">Date</th><th scope="col">Product</th><th scope="col">Movement</th><th scope="col">Balance</th><th scope="col">Reason</th><th scope="col">Actor</th></tr></thead><tbody>
            @forelse ($this->movements as $movement)
                <tr wire:key="movement-{{ $movement->id }}"><td class="text-nowrap"><span class="d-block">{{ $movement->created_at->format('d M Y') }}</span><small class="aureon-muted">{{ $movement->created_at->format('H:i:s') }}</small></td><td><span class="d-block fw-semibold">{{ $movement->product->name }}</span><code class="aureon-event-name">{{ $movement->product->sku }}</code></td><td><span class="badge aureon-stock-badge {{ $movement->quantity_delta > 0 ? 'aureon-stock-badge--healthy' : 'aureon-stock-badge--out' }}">{{ $movement->quantity_delta > 0 ? '+' : '' }}{{ number_format($movement->quantity_delta) }}</span><small class="aureon-muted d-block mt-1">{{ $movement->type->label() }}</small></td><td>{{ number_format($movement->balance_before) }} <i class="ti ti-arrow-right aureon-muted mx-1"></i> {{ number_format($movement->balance_after) }}</td><td>{{ $movement->note ?: 'No note' }}@if ($movement->reference)<small class="aureon-muted d-block">{{ class_basename($movement->reference) }} #{{ $movement->reference_id }}</small>@endif</td><td>{{ $movement->creator?->display_name ?? 'System' }}</td></tr>
            @empty
                <tr><td colspan="6" class="text-center py-5"><span class="aureon-empty-state__icon"><i class="ti ti-history-off"></i></span><h4 class="fs-16 mb-1">No movements found</h4><p class="aureon-muted mb-0">Stock changes will appear here as immutable ledger entries.</p></td></tr>
            @endforelse
        </tbody></table></div>
        @if ($this->movements->hasPages())<div class="card-footer">{{ $this->movements->onEachSide(1)->links() }}</div>@endif
    </section>

    @if ($dialog === 'adjust' && $this->selectedStock)
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="stock-adjustment-title" wire:keydown.escape.window="closeDialog"><div class="modal-dialog modal-dialog-centered" role="document"><form class="modal-content" wire:submit="adjust"><div class="modal-header"><div><h3 id="stock-adjustment-title" class="modal-title fs-18">Adjust stock</h3><p class="aureon-muted fs-12 mb-0">{{ $this->selectedStock->product->name }} · {{ $this->selectedStock->product->sku }}</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close stock adjustment"></button></div><div class="modal-body">
            @error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror
            <div class="aureon-stock-current mb-4"><span>Current balance</span><strong>{{ number_format($this->selectedStock->on_hand) }} {{ \Illuminate\Support\Str::plural($this->selectedStock->product->unit_label, $this->selectedStock->on_hand) }}</strong></div>
            <div class="mb-3"><label class="form-label d-block">Direction</label><div class="btn-group w-100" role="group"><input id="stock-increase" type="radio" class="btn-check" value="increase" wire:model="form.direction"><label for="stock-increase" class="btn btn-outline-success"><i class="ti ti-plus me-2"></i>Increase</label><input id="stock-decrease" type="radio" class="btn-check" value="decrease" wire:model="form.direction"><label for="stock-decrease" class="btn btn-outline-danger"><i class="ti ti-minus me-2"></i>Decrease</label></div>@error('form.direction')<div class="text-danger fs-12 mt-1">{{ $message }}</div>@enderror</div>
            <div class="mb-3"><label for="stock-quantity" class="form-label">Quantity <span class="text-danger">*</span></label><input id="stock-quantity" type="number" min="1" class="form-control @error('form.quantity') is-invalid @enderror" wire:model="form.quantity">@error('form.quantity')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div><label for="stock-note" class="form-label">Reason <span class="text-danger">*</span></label><textarea id="stock-note" rows="3" class="form-control @error('form.note') is-invalid @enderror" wire:model="form.note" placeholder="Count correction, received shipment, damage, or other reason"></textarea>@error('form.note')<div class="invalid-feedback">{{ $message }}</div>@enderror<p class="aureon-muted fs-12 mt-2 mb-0">The resulting ledger entry cannot be edited or deleted.</p></div>
        </div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary" wire:loading.attr="disabled" wire:target="adjust"><i class="ti ti-check me-2"></i><span wire:loading.remove wire:target="adjust">Post adjustment</span><span wire:loading wire:target="adjust">Posting...</span></button></div></form></div></div><button type="button" class="modal-backdrop fade show border-0 w-100" wire:click="closeDialog" aria-label="Close stock adjustment"></button>
    @endif
</div>
