@extends('property-booking::layouts.storefront')

@section('title', 'Review your stay')
@section('meta_description', 'Review your selected accommodation dates, occupancy, and current total before checkout.')
@section('nav', 'selection')

@section('content')
    @php($localStart = $quote->startsAt->timezone($property->timezone))
    @php($localEnd = $quote->endsAt->timezone($property->timezone))
    <section class="pb-stay-process-hero"><div class="container-xxl"><p class="pb-storefront-eyebrow">Step 1 of 2</p><h1>Review your stay</h1><p>Your selection is re-priced from current availability every time this page loads.</p></div></section>
    <section class="pb-stay-review"><div class="container-xxl pb-stay-review__grid"><article><div class="pb-stay-review__heading"><div><p>{{ $quote->propertyName }}</p><h2>{{ $quote->unitTypeName }}</h2><span>{{ $quote->ratePlanName }}</span></div><span class="pb-storefront-badge">{{ $quote->availableUnitCount }} available</span></div><dl class="pb-stay-review__facts"><div><dt>Arrival</dt><dd>{{ $localStart->format('D, d M Y') }}<small>{{ $localStart->format('H:i') }}</small></dd></div><div><dt>Departure</dt><dd>{{ $localEnd->format('D, d M Y') }}<small>{{ $localEnd->format('H:i') }}</small></dd></div><div><dt>Occupancy</dt><dd>{{ $quote->adults }} {{ \Illuminate\Support\Str::plural('adult', $quote->adults) }}<small>{{ $quote->children }} children, {{ $quote->infants }} infants</small></dd></div><div><dt>Duration</dt><dd>{{ $quote->calculation->billableUnits }} {{ \Illuminate\Support\Str::plural($quote->calculation->pricingUnit->label(), $quote->calculation->billableUnits) }}<small>{{ $property->timezone }}</small></dd></div></dl><div class="pb-stay-review__assurance"><i data-lucide="shield-check" aria-hidden="true"></i><div><strong>No unit number is exposed or chosen here.</strong><span>A suitable concrete unit is locked and allocated only when the booking transaction succeeds.</span></div></div></article><aside class="pb-stay-summary"><p class="pb-storefront-eyebrow">Current price</p><h2>Stay summary</h2><dl><div><dt>Accommodation</dt><dd>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($quote->calculation->subtotalMinor, $quote->calculation->currency) }}</dd></div><div><dt>Tax {{ $quote->calculation->taxInclusive ? '(included)' : '' }}</dt><dd>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($quote->calculation->taxMinor, $quote->calculation->currency) }}</dd></div><div class="pb-stay-summary__total"><dt>Total</dt><dd>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($quote->calculation->totalMinor, $quote->calculation->currency) }}</dd></div><div><dt>Deposit expected</dt><dd>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($quote->calculation->requiredDepositMinor, $quote->calculation->currency) }}</dd></div></dl><a class="pb-storefront-button" href="{{ route('property-booking.storefront.checkout.index') }}">Guest details <i data-lucide="arrow-right" aria-hidden="true"></i></a><a class="pb-storefront-text-link" href="{{ route('property-booking.storefront.properties.show', ['property' => $property->slug]) }}#availability"><i data-lucide="arrow-left" aria-hidden="true"></i>Change selection</a></aside></div></section>
@endsection
