@extends($reportContext->orientation->layout())

@section('content')
    <section class="report-section"><div class="metrics"><div class="metric"><strong>{{ $document->stayCount() }}</strong>{{ \Illuminate\Support\Str::plural('Stay', $document->stayCount()) }}</div><div class="metric"><strong>{{ $document->statusLabel }}</strong>Booking</div><div class="metric"><strong>{{ $document->paymentStatusLabel }}</strong>Payment</div><div class="metric"><strong>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($document->totalMinor, $document->currency) }}</strong>Total</div></div><div class="filters"><strong>Guest:</strong> {{ $document->guestName }} | <strong>Property:</strong> {{ $document->propertyName }} | <strong>Placed:</strong> {{ $document->placedAt?->format('d M Y, H:i') }}</div></section>
    <section class="report-section"><h2 class="section-title">Stay details</h2><table><thead><tr><th style="width:7%">#</th><th>Accommodation</th><th style="width:18%">Occupancy</th><th style="width:18%">Rate</th>@if($orientation === 'landscape')<th style="width:15%">Tax</th>@endif<th style="width:19%">Total</th></tr></thead><tbody>@foreach($document->stays as $stay)<tr><td class="text-center">{{ $loop->iteration }}</td><td><strong>{{ $stay->unitTypeName }}</strong><br>{{ $stay->ratePlanName }} | {{ $stay->billableUnits }} {{ \Illuminate\Support\Str::plural($stay->pricingUnitLabel, $stay->billableUnits) }}</td><td>{{ $stay->adults }} adults<br>{{ $stay->children }} children</td><td>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($stay->unitRateMinor, $document->currency) }}</td>@if($orientation === 'landscape')<td>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($stay->taxMinor, $document->currency) }}</td>@endif<td>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($stay->totalMinor, $document->currency) }}</td></tr>@endforeach</tbody></table></section>
    <section class="report-section"><h2 class="section-title">Schedule and guest</h2><table><tbody><tr><td><strong>Arrival</strong><br>{{ $document->startsAt->format('D, d M Y, H:i') }}</td><td><strong>Departure</strong><br>{{ $document->endsAt->format('D, d M Y, H:i') }}</td></tr><tr><td><strong>Guest</strong><br>{{ $document->guestName }}@if($document->guestEmail)<br>{{ $document->guestEmail }}@endif</td><td><strong>Contact</strong><br>{{ $document->guestPhone ?: 'Not supplied' }}<br>{{ $document->timezone }}</td></tr></tbody></table></section>
    <section class="report-section"><h2 class="section-title">Booking totals</h2><table><tbody><tr><td><strong>Accommodation</strong></td><td>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($document->accommodationSubtotalMinor, $document->currency) }}</td></tr><tr><td><strong>Tax {{ $document->taxInclusive ? '(included)' : '' }}</strong></td><td>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($document->taxMinor, $document->currency) }}</td></tr><tr><td><strong>Booking total</strong></td><td><strong>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($document->totalMinor, $document->currency) }}</strong></td></tr><tr><td><strong>Deposit expected</strong></td><td>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($document->requiredDepositMinor, $document->currency) }}</td></tr><tr><td><strong>Paid / balance</strong></td><td>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($document->paidMinor, $document->currency) }} / {{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($document->balanceMinor, $document->currency) }}</td></tr><tr><td><strong>Payment preference</strong></td><td>{{ $document->paymentPreferenceLabel }}</td></tr></tbody></table></section>
    @if($document->specialRequests)<section class="report-section"><h2 class="section-title">Guest request</h2><p>{{ $document->specialRequests }}</p></section>@endif
@endsection
