<footer class="report-footer">
    Generated by {{ $reportContext->generatedBy }} on {{ $reportContext->generatedAt->format('d M Y, H:i') }} |
    Page <span class="page-number"></span>@if ($totalPages) of {{ $totalPages }}@endif |
    {{ $institutionProfile->shortName }}
</footer>

