<div id="property-booking-booking-manager" class="pb-workspace">
    @php
        $stats = $this->statistics;
    @endphp
    @include('property-booking::livewire.admin.partials.stat-grid', ['cards' => [
        ['label' => 'Recorded bookings', 'value' => $stats['total'], 'icon' => 'ti-calendar-check', 'color' => 'var(--aureon-primary)'],
        ['label' => 'Active reservations', 'value' => $stats['active'], 'icon' => 'ti-calendar-event', 'color' => '#2c6e93'],
        ['label' => 'Guests in house', 'value' => $stats['in_house'], 'icon' => 'ti-door-enter', 'color' => '#2f7d64'],
        ['label' => 'Action queue', 'value' => $stats['action'], 'icon' => 'ti-alert-circle', 'color' => '#9b6a23'],
    ]])

    @if (session('success'))<div class="alert alert-success alert-dismissible fade show" role="status">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>@endif
    @error('management')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror

    <section class="card aureon-panel aureon-table-panel" aria-labelledby="booking-register-title">
        <div class="card-header d-flex align-items-center justify-content-between gap-3 flex-wrap">
            <div><h3 id="booking-register-title" class="card-title mb-1">Booking register</h3><p class="aureon-muted fs-12 mb-0">Current reservation, stay, payment, and assignment state</p></div>
            <span class="pb-badge pb-badge--neutral">{{ number_format($this->bookings->total()) }} results</span>
        </div>
        <div class="pb-filterbar pb-filterbar--booking">
            <div class="pb-filterbar__search"><label for="booking-search" class="visually-hidden">Search bookings</label><i class="ti ti-search"></i><input id="booking-search" type="search" class="form-control" placeholder="Number, guest, email, phone" wire:model.live.debounce.300ms="search"></div>
            <div><label for="booking-property-filter" class="visually-hidden">Property</label><select id="booking-property-filter" class="form-select" wire:model.live="propertyFilter"><option value="">All properties</option>@foreach($this->propertyOptions as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select></div>
            <div><label for="booking-channel-filter" class="visually-hidden">Channel</label><select id="booking-channel-filter" class="form-select" wire:model.live="channelFilter"><option value="">All channels</option>@foreach(\App\Modules\PropertyBooking\Bookings\Enums\BookingChannel::cases() as $channel)<option value="{{ $channel->value }}">{{ $channel->label() }}</option>@endforeach</select></div>
            <div><label for="booking-status-filter" class="visually-hidden">Booking status</label><select id="booking-status-filter" class="form-select" wire:model.live="statusFilter"><option value="">All booking states</option>@foreach(\App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::cases() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div>
            <div><label for="booking-stay-filter" class="visually-hidden">Stay status</label><select id="booking-stay-filter" class="form-select" wire:model.live="stayFilter"><option value="">All stay states</option>@foreach(\App\Modules\PropertyBooking\Bookings\Enums\StayStatus::cases() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div>
            <div><label for="booking-payment-filter" class="visually-hidden">Payment status</label><select id="booking-payment-filter" class="form-select" wire:model.live="paymentFilter"><option value="">All settlement states</option>@foreach(\App\Modules\PropertyBooking\Bookings\Enums\BookingPaymentStatus::cases() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div>
            <button type="button" class="btn btn-outline-secondary" wire:click="clearFilters"><i class="ti ti-filter-off me-2"></i>Clear</button>
        </div>
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0 pb-table pb-table--bookings">
                <thead><tr><th>Booking</th><th>Guest</th><th>Stay</th><th>Accommodation</th><th>Settlement</th><th>State</th><th class="text-end">Actions</th></tr></thead>
                <tbody>
                    @forelse($this->bookings as $booking)
                        @php
                            $assignment = $booking->stays->first()?->activeAssignment;
                            $statusClass = match($booking->status) {
                                \App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::Confirmed, \App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::Completed => 'pb-badge--success',
                                \App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::Cancelled, \App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::NoShow, \App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::Expired => 'pb-badge--danger',
                                default => 'pb-badge--warning',
                            };
                            $paymentClass = match($booking->payment_status) {
                                \App\Modules\PropertyBooking\Bookings\Enums\BookingPaymentStatus::Paid => 'pb-badge--success',
                                \App\Modules\PropertyBooking\Bookings\Enums\BookingPaymentStatus::Partial => 'pb-badge--warning',
                                \App\Modules\PropertyBooking\Bookings\Enums\BookingPaymentStatus::Refunded => 'pb-badge--info',
                                default => 'pb-badge--neutral',
                            };
                        @endphp
                        <tr wire:key="booking-{{ $booking->id }}">
                            <td><strong class="d-block">{{ $booking->booking_number }}</strong><small class="aureon-muted">{{ $booking->channel->label() }} &middot; {{ $booking->placed_at?->timezone($booking->property_timezone)->format('d M Y H:i') }}</small></td>
                            <td><span class="d-block">{{ trim($booking->guest_first_name.' '.$booking->guest_last_name) }}</span><small class="aureon-muted">{{ $booking->guest_phone ?: ($booking->guest_email ?: 'No contact recorded') }}</small></td>
                            <td><strong class="d-block">{{ $booking->starts_at->timezone($booking->property_timezone)->format('d M Y H:i') }}</strong><small class="aureon-muted">to {{ $booking->ends_at->timezone($booking->property_timezone)->format('d M Y H:i') }}</small></td>
                            <td><span class="d-block">{{ $booking->property->name }}</span><small class="aureon-muted">{{ $assignment?->unit?->display_name ?: ($assignment?->unit?->code ?: 'Allocation pending') }}</small></td>
                            <td><strong class="d-block">{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($booking->total_minor, $booking->currency) }}</strong><span class="pb-badge {{ $paymentClass }} mt-1">{{ $booking->payment_status->label() }}</span>@if($booking->balance_minor > 0)<small class="d-block aureon-muted mt-1">Due {{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($booking->balance_minor, $booking->currency) }}</small>@endif</td>
                            <td><span class="pb-badge {{ $statusClass }}">{{ $booking->status->label() }}</span><small class="d-block aureon-muted mt-1">{{ $booking->stay_status->label() }}</small></td>
                            <td class="text-end text-nowrap">
                                <button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openDetails({{ $booking->id }})" data-bs-toggle="tooltip" title="View booking" aria-label="View {{ $booking->booking_number }}"><i class="ti ti-eye"></i></button>
                                <div class="dropdown d-inline-block">
                                    <button class="btn btn-icon btn-sm btn-outline-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Actions for {{ $booking->booking_number }}"><i class="ti ti-dots-vertical"></i></button>
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        @can('update', $booking)
                                            @if($booking->status === \App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::Pending)<li><button class="dropdown-item" type="button" wire:click="confirmBooking({{ $booking->id }})" wire:confirm="Confirm this booking?"><i class="ti ti-circle-check me-2"></i>Confirm booking</button></li>@endif
                                            @if(!$booking->status->isTerminal())<li><button class="dropdown-item" type="button" wire:click="openModification({{ $booking->id }})"><i class="ti ti-calendar-time me-2"></i>Modify dates</button></li>@endif
                                            @if($assignment)<li><button class="dropdown-item" type="button" wire:click="openMove({{ $booking->id }})"><i class="ti ti-transfer me-2"></i>Move unit</button></li>@endif
                                        @endcan
                                        @can('checkIn', $booking) @if($booking->status === \App\Modules\PropertyBooking\Bookings\Enums\BookingStatus::Confirmed && $booking->stay_status === \App\Modules\PropertyBooking\Bookings\Enums\StayStatus::Expected)<li><button class="dropdown-item" type="button" wire:click="openCheckIn({{ $booking->id }})"><i class="ti ti-door-enter me-2"></i>Check in</button></li>@endif @endcan
                                        @can('checkOut', $booking) @if($booking->stay_status === \App\Modules\PropertyBooking\Bookings\Enums\StayStatus::CheckedIn)<li><button class="dropdown-item" type="button" wire:click="openCheckOut({{ $booking->id }})"><i class="ti ti-door-exit me-2"></i>Check out</button></li>@endif @endcan
                                        @can('create', \App\Modules\PropertyBooking\Bookings\Models\BookingPayment::class) @if($booking->balance_minor > 0 && !$booking->status->isTerminal())<li><button class="dropdown-item" type="button" wire:click="openPayment({{ $booking->id }})"><i class="ti ti-credit-card-pay me-2"></i>Record payment</button></li>@endif @endcan
                                        @can('update', $booking)
                                            @if(!$booking->status->isTerminal() && $booking->stay_status === \App\Modules\PropertyBooking\Bookings\Enums\StayStatus::Expected)<li><hr class="dropdown-divider"></li><li><button class="dropdown-item" type="button" wire:click="openNoShow({{ $booking->id }})"><i class="ti ti-user-x me-2"></i>Mark no-show</button></li><li><button class="dropdown-item text-danger" type="button" wire:click="openCancellation({{ $booking->id }})"><i class="ti ti-calendar-cancel me-2"></i>Cancel booking</button></li>@endif
                                        @endcan
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="7"><div class="pb-empty"><i class="ti ti-calendar-off"></i><strong>No bookings match this view</strong></div></td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="card-footer d-flex align-items-center justify-content-between gap-3 flex-wrap"><div class="d-flex align-items-center gap-2"><label for="booking-per-page" class="aureon-muted fs-11">Rows</label><select id="booking-per-page" class="form-select form-select-sm pb-page-size" wire:model.live="perPage"><option>10</option><option>15</option><option>25</option><option>50</option></select></div>@if($this->bookings->hasPages()){{ $this->bookings->links() }}@endif</div>
    </section>

    @php
        $selected = $this->selectedBooking;
    @endphp
    @if($dialog !== '' && $selected)
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="booking-dialog-title" wire:keydown.escape.window="closeDialog">
            <div class="modal-dialog {{ $dialog === 'details' ? 'modal-xl' : 'modal-lg' }} modal-dialog-centered modal-dialog-scrollable">
                @if($dialog === 'details')
                    <div class="modal-content">
                        <div class="modal-header"><div><h3 id="booking-dialog-title" class="modal-title fs-18">{{ $selected->booking_number }}</h3><p class="aureon-muted fs-12 mb-0">{{ $selected->property_name }} &middot; {{ $selected->channel->label() }}</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close booking details"></button></div>
                        <div class="modal-body"><div class="pb-booking-detail-grid">
                            <section><h4>Stay and guest</h4><dl class="pb-detail-list"><div><dt>Primary guest</dt><dd>{{ trim($selected->guest_first_name.' '.$selected->guest_middle_name.' '.$selected->guest_last_name) }}</dd></div><div><dt>Contact</dt><dd>{{ $selected->guest_phone ?: 'Not supplied' }}<br>{{ $selected->guest_email ?: 'Not supplied' }}</dd></div><div><dt>Arrival</dt><dd>{{ $selected->starts_at->timezone($selected->property_timezone)->format('d M Y, H:i') }}</dd></div><div><dt>Departure</dt><dd>{{ $selected->ends_at->timezone($selected->property_timezone)->format('d M Y, H:i') }}</dd></div><div><dt>Occupancy</dt><dd>{{ $selected->adult_count }} adults, {{ $selected->child_count }} children, {{ $selected->infant_count }} infants</dd></div></dl></section>
                            <section><h4>Status and settlement</h4><dl class="pb-detail-list"><div><dt>Booking</dt><dd>{{ $selected->status->label() }}</dd></div><div><dt>Stay</dt><dd>{{ $selected->stay_status->label() }}</dd></div><div><dt>Payment</dt><dd>{{ $selected->payment_status->label() }}</dd></div><div><dt>Total</dt><dd>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($selected->total_minor, $selected->currency) }}</dd></div><div><dt>Paid / balance</dt><dd>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($selected->paid_minor, $selected->currency) }} / {{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($selected->balance_minor, $selected->currency) }}</dd></div></dl></section>
                            <section class="pb-booking-detail-grid__wide"><h4>Reserved accommodation</h4><div class="pb-detail-lines">@foreach($selected->stays as $stay)<article><div><strong>{{ $stay->unit_type_name }}</strong><small>{{ $stay->rate_plan_name }} &middot; {{ $stay->billable_units }} {{ \Illuminate\Support\Str::plural($stay->pricing_unit->label(), $stay->billable_units) }}</small></div><div class="text-end"><strong>{{ $stay->activeAssignment?->unit?->display_name ?: ($stay->activeAssignment?->unit?->code ?: 'Released') }}</strong><small>{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($stay->total_minor, $selected->currency) }}</small></div></article>@endforeach</div></section>
                            @if($selected->payments->isNotEmpty())<section class="pb-booking-detail-grid__wide"><h4>Payments</h4><div class="table-responsive"><table class="table pb-table pb-table--compact mb-0"><thead><tr><th>Method</th><th>Reference</th><th>Recorded</th><th class="text-end">Amount</th></tr></thead><tbody>@foreach($selected->payments as $payment)<tr><td>{{ $payment->method->label() }}</td><td>{{ $payment->reference ?: 'Not supplied' }}</td><td>{{ $payment->created_at?->format('d M Y H:i') }}</td><td class="text-end">{{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($payment->amount_minor, $selected->currency) }}</td></tr>@endforeach</tbody></table></div></section>@endif
                            @if($selected->special_requests || $selected->internal_note)<section class="pb-booking-detail-grid__wide"><h4>Operational notes</h4>@if($selected->special_requests)<p><strong>Guest request:</strong> {{ $selected->special_requests }}</p>@endif @if($selected->internal_note)<p><strong>Internal:</strong> {{ $selected->internal_note }}</p>@endif</section>@endif
                        </div></div>
                        <div class="modal-footer"><button type="button" class="btn btn-primary" wire:click="closeDialog">Done</button></div>
                    </div>
                @elseif(in_array($dialog, ['cancel', 'no-show'], true))
                    <form class="modal-content" wire:submit="{{ $dialog === 'cancel' ? 'cancelBooking' : 'markNoShow' }}"><div class="modal-header"><div><h3 id="booking-dialog-title" class="modal-title fs-18">{{ $dialog === 'cancel' ? 'Cancel booking' : 'Mark no-show' }}</h3><p class="aureon-muted fs-12 mb-0">{{ $selected->booking_number }} &middot; allocation will be released</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close"></button></div><div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror<label for="booking-action-reason" class="form-label">Operational reason <span class="text-danger">*</span></label><textarea id="booking-action-reason" rows="4" class="form-control @error('actionReason') is-invalid @enderror" wire:model="actionReason"></textarea>@error('actionReason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Keep booking</button><button type="submit" class="btn btn-danger">{{ $dialog === 'cancel' ? 'Cancel booking' : 'Mark no-show' }}</button></div></form>
                @elseif(in_array($dialog, ['check-in', 'check-out'], true))
                    <form class="modal-content" wire:submit="{{ $dialog === 'check-in' ? 'checkIn' : 'checkOut' }}"><div class="modal-header"><div><h3 id="booking-dialog-title" class="modal-title fs-18">{{ $dialog === 'check-in' ? 'Check in guest' : 'Check out guest' }}</h3><p class="aureon-muted fs-12 mb-0">{{ $selected->booking_number }} &middot; {{ trim($selected->guest_first_name.' '.$selected->guest_last_name) }}</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close"></button></div><div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror<div class="alert alert-info mb-3">Normal timing and settlement policies are checked when this action runs.</div><label for="booking-override-reason" class="form-label">Exception reason</label><textarea id="booking-override-reason" rows="3" class="form-control @error('overrideReason') is-invalid @enderror" wire:model="overrideReason" placeholder="Required only when overriding a timing or settlement exception"></textarea>@error('overrideReason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary">{{ $dialog === 'check-in' ? 'Complete check-in' : 'Complete check-out' }}</button></div></form>
                @elseif($dialog === 'modify')
                    <form class="modal-content" wire:submit="modifyBooking"><div class="modal-header"><div><h3 id="booking-dialog-title" class="modal-title fs-18">Modify stay dates</h3><p class="aureon-muted fs-12 mb-0">Availability and price are recalculated at save</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close"></button></div><div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror<div class="row g-3"><div class="col-md-6"><label for="booking-start" class="form-label">Arrival <span class="text-danger">*</span></label><input id="booking-start" type="datetime-local" class="form-control @error('modificationForm.startsAt') is-invalid @enderror" wire:model="modificationForm.startsAt">@error('modificationForm.startsAt')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label for="booking-end" class="form-label">Departure <span class="text-danger">*</span></label><input id="booking-end" type="datetime-local" class="form-control @error('modificationForm.endsAt') is-invalid @enderror" wire:model="modificationForm.endsAt">@error('modificationForm.endsAt')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label for="booking-modification-reason" class="form-label">Reason <span class="text-danger">*</span></label><textarea id="booking-modification-reason" rows="3" class="form-control @error('modificationForm.reason') is-invalid @enderror" wire:model="modificationForm.reason"></textarea>@error('modificationForm.reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary">Reprice and save</button></div></form>
                @elseif($dialog === 'move')
                    <form class="modal-content" wire:submit="moveUnit"><div class="modal-header"><div><h3 id="booking-dialog-title" class="modal-title fs-18">Move accommodation unit</h3><p class="aureon-muted fs-12 mb-0">Only ready, compatible, unallocated units are listed</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close"></button></div><div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror<div class="row g-3"><div class="col-12"><label for="booking-target-unit" class="form-label">Target unit <span class="text-danger">*</span></label><select id="booking-target-unit" class="form-select @error('targetUnitId') is-invalid @enderror" wire:model="targetUnitId"><option value="">Select available unit</option>@foreach($this->moveTargets as $unit)<option value="{{ $unit->id }}">{{ $unit->display_name ?: $unit->code }} &middot; {{ $unit->floor_label ?: $unit->code }}</option>@endforeach</select>@error('targetUnitId')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label for="booking-move-reason" class="form-label">Reason <span class="text-danger">*</span></label><textarea id="booking-move-reason" rows="3" class="form-control @error('actionReason') is-invalid @enderror" wire:model="actionReason"></textarea>@error('actionReason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary" @disabled($this->moveTargets->isEmpty())>Move unit</button></div></form>
                @elseif($dialog === 'payment')
                    <form class="modal-content" wire:submit="recordPayment"><div class="modal-header"><div><h3 id="booking-dialog-title" class="modal-title fs-18">Record booking payment</h3><p class="aureon-muted fs-12 mb-0">Outstanding {{ \App\Modules\PropertyBooking\Support\MoneyFormatter::format($selected->balance_minor, $selected->currency) }} &middot; non-cash administration entry</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close"></button></div><div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror<div class="row g-3"><div class="col-md-4"><label for="booking-payment-method" class="form-label">Method <span class="text-danger">*</span></label><select id="booking-payment-method" class="form-select @error('paymentForm.method') is-invalid @enderror" wire:model="paymentForm.method">@foreach(\App\Modules\PropertyBooking\Bookings\Livewire\Forms\BookingAdministrationPaymentForm::methods() as $method)<option value="{{ $method->value }}">{{ $method->label() }}</option>@endforeach</select>@error('paymentForm.method')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4"><label for="booking-payment-amount" class="form-label">Amount ({{ $selected->currency }}) <span class="text-danger">*</span></label><input id="booking-payment-amount" type="text" inputmode="decimal" class="form-control @error('paymentForm.amount') is-invalid @enderror" wire:model="paymentForm.amount">@error('paymentForm.amount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4"><label for="booking-payment-reference" class="form-label">Reference <span class="text-danger">*</span></label><input id="booking-payment-reference" type="text" class="form-control @error('paymentForm.reference') is-invalid @enderror" wire:model="paymentForm.reference">@error('paymentForm.reference')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary">Record payment</button></div></form>
                @endif
            </div>
        </div><div class="modal-backdrop fade show"></div>
    @endif
</div>
