<div id="property-booking-rate-plan-manager" class="pb-workspace mb-4">
    @php($stats = $this->statistics)
    @include('property-booking::livewire.admin.partials.stat-grid', ['cards' => [
        ['label' => 'Rate plans', 'value' => $stats['total'], 'icon' => 'ti-receipt-2', 'color' => 'var(--aureon-primary)'],
        ['label' => 'Active', 'value' => $stats['active'], 'icon' => 'ti-circle-check', 'color' => '#2f7d64'],
        ['label' => 'Drafts', 'value' => $stats['draft'], 'icon' => 'ti-file-pencil', 'color' => '#2c6e93'],
        ['label' => 'Public', 'value' => $stats['public'], 'icon' => 'ti-world', 'color' => '#9b6a23'],
    ]])

    @if(session('success'))<div class="alert alert-success alert-dismissible fade show" role="status">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>@endif
    @error('management')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror

    <section class="card aureon-panel aureon-table-panel" aria-labelledby="rate-plan-title">
        <div class="card-header d-flex align-items-center justify-content-between gap-3 flex-wrap"><div><h3 id="rate-plan-title" class="card-title mb-1">Rate plans</h3><p class="aureon-muted fs-12 mb-0">Pricing units, occupancy, tax, deposit, and cancellation policy</p></div>@can(\App\Modules\PropertyBooking\Support\PropertyBookingPermission::MANAGE_RATES)<button type="button" class="btn btn-primary" wire:click="openCreate"><i class="ti ti-receipt-2 me-2"></i>Add rate plan</button>@endcan</div>
        <div class="pb-filterbar">
            <div class="pb-filterbar__search"><label for="rate-search" class="visually-hidden">Search rates</label><i class="ti ti-search"></i><input id="rate-search" type="search" class="form-control" placeholder="Name or code" wire:model.live.debounce.300ms="search"></div>
            <div><label for="rate-property" class="visually-hidden">Property</label><select id="rate-property" class="form-select" wire:model.live="propertyFilter"><option value="">All properties</option>@foreach($this->propertyOptions as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select></div>
            <div><label for="rate-status" class="visually-hidden">Status</label><select id="rate-status" class="form-select" wire:model.live="statusFilter"><option value="">All statuses</option>@foreach($this->statuses as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div>
            <button type="button" class="btn btn-outline-secondary" wire:click="clearFilters"><i class="ti ti-filter-off me-2"></i>Clear</button>
        </div>
        <div class="table-responsive"><table class="table table-hover align-middle mb-0 pb-table pb-table--rates">
            <thead><tr><th>Rate plan</th><th>Property and unit type</th><th>Price</th><th>Restrictions</th><th>Visibility</th><th class="text-end">Actions</th></tr></thead>
            <tbody>
                @forelse($this->ratePlans as $rate)
                    @php($statusClass = match($rate->status) { \App\Modules\PropertyBooking\Pricing\Enums\RatePlanStatus::Active => 'pb-badge--success', \App\Modules\PropertyBooking\Pricing\Enums\RatePlanStatus::Archived => 'pb-badge--neutral', default => 'pb-badge--info' })
                    <tr wire:key="rate-plan-{{ $rate->id }}">
                        <td><strong class="d-block">{{ $rate->name }}</strong><code class="pb-code">{{ $rate->code }}</code><small class="d-block aureon-muted mt-1">{{ $rate->pricing_unit->label() }}</small></td>
                        <td><span class="d-block">{{ $rate->property->name }}</span><small class="aureon-muted">{{ $rate->unitType->name }}</small></td>
                        <td><strong class="d-block">{{ $this->money($rate->base_rate_minor, $rate->currency) }}</strong><small class="aureon-muted">Tax {{ number_format($rate->tax_rate_bps / 100, 2) }}% {{ $rate->is_tax_inclusive ? 'inclusive' : 'exclusive' }}</small></td>
                        <td><span class="d-block">{{ $rate->minimum_units }}–{{ $rate->maximum_units ?? 'No maximum' }} {{ str($rate->pricing_unit->label())->plural($rate->maximum_units ?? 2) }}</span><small class="aureon-muted">{{ number_format($rate->overrides_count) }} date overrides</small></td>
                        <td><span class="pb-badge {{ $statusClass }}">{{ $rate->status->label() }}</span><span class="pb-badge {{ $rate->is_public ? 'pb-badge--info' : 'pb-badge--neutral' }} ms-1">{{ $rate->is_public ? 'Public' : 'Private' }}</span></td>
                        <td class="text-end text-nowrap">@can('update', $rate)<button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openEdit({{ $rate->id }})" data-bs-toggle="tooltip" title="Edit rate plan" aria-label="Edit {{ $rate->name }}"><i class="ti ti-edit"></i></button><select class="form-select form-select-sm pb-inline-select" aria-label="Change status for {{ $rate->name }}" wire:change="changeStatus({{ $rate->id }}, $event.target.value)"><option value="">Status</option>@foreach($this->statuses as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select>@endcan</td>
                    </tr>
                @empty
                    <tr><td colspan="6"><div class="pb-empty"><i class="ti ti-receipt-off"></i><strong>No rate plans match this view</strong></div></td></tr>
                @endforelse
            </tbody>
        </table></div>
        @if($this->ratePlans->hasPages())<div class="card-footer">{{ $this->ratePlans->links() }}</div>@endif
    </section>

    @if($dialog === 'form')
        @php($editing = $selectedRatePlanId !== null)
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="rate-plan-form-title" wire:keydown.escape.window="closeDialog"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><form class="modal-content" wire:submit="save">
            <div class="modal-header"><div><h3 id="rate-plan-form-title" class="modal-title fs-18">{{ $editing ? 'Edit rate plan' : 'Create rate plan' }}</h3><p class="aureon-muted fs-12 mb-0">Authoritative integer-money and booking-policy configuration</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close rate-plan form"></button></div>
            <div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror
                <fieldset class="pb-form-section"><legend>Identity and base price</legend><div class="row g-3">
                    <div class="col-lg-5"><label for="rate-form-type" class="form-label">Unit type <span class="text-danger">*</span></label><select id="rate-form-type" class="form-select @error('form.unitTypeId') is-invalid @enderror" wire:model.live="form.unitTypeId" @disabled($editing)><option value="">Select unit type</option>@foreach($this->unitTypeOptions as $type)<option value="{{ $type->id }}">{{ $type->name }} · {{ $type->code }}</option>@endforeach</select>@error('form.unitTypeId')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-lg-4"><label for="rate-form-name" class="form-label">Name <span class="text-danger">*</span></label><input id="rate-form-name" type="text" class="form-control @error('form.name') is-invalid @enderror" wire:model="form.name">@error('form.name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-lg-3"><label for="rate-form-code" class="form-label">Code <span class="text-danger">*</span></label><input id="rate-form-code" type="text" class="form-control @error('form.code') is-invalid @enderror" wire:model="form.code">@error('form.code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-12"><label for="rate-form-description" class="form-label">Description</label><textarea id="rate-form-description" rows="3" class="form-control @error('form.description') is-invalid @enderror" wire:model="form.description"></textarea>@error('form.description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-4"><label for="rate-form-pricing-unit" class="form-label">Pricing unit <span class="text-danger">*</span></label><select id="rate-form-pricing-unit" class="form-select @error('form.pricingUnit') is-invalid @enderror" wire:model="form.pricingUnit">@foreach($this->pricingUnits as $unit)<option value="{{ $unit->value }}">{{ $unit->label() }}</option>@endforeach</select>@error('form.pricingUnit')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-4"><label for="rate-form-base" class="form-label">Base rate <span class="text-danger">*</span></label><div class="input-group"><span class="input-group-text">{{ $form->currency }}</span><input id="rate-form-base" type="text" inputmode="decimal" class="form-control @error('form.baseRate') is-invalid @enderror" wire:model="form.baseRate">@error('form.baseRate')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
                    <div class="col-md-4"><label for="rate-form-currency" class="form-label">Currency</label><input id="rate-form-currency" type="text" maxlength="3" class="form-control text-uppercase @error('form.currency') is-invalid @enderror" wire:model="form.currency" readonly>@error('form.currency')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                </div></fieldset>
                <fieldset class="pb-form-section"><legend>Occupancy and duration</legend><div class="row g-3">
                    <div class="col-sm-6 col-lg-3"><label for="rate-adults" class="form-label">Included adults</label><input id="rate-adults" type="number" min="0" class="form-control @error('form.includedAdults') is-invalid @enderror" wire:model="form.includedAdults">@error('form.includedAdults')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-sm-6 col-lg-3"><label for="rate-children" class="form-label">Included children</label><input id="rate-children" type="number" min="0" class="form-control @error('form.includedChildren') is-invalid @enderror" wire:model="form.includedChildren">@error('form.includedChildren')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-sm-6 col-lg-3"><label for="rate-extra-adult" class="form-label">Extra adult</label><input id="rate-extra-adult" type="text" inputmode="decimal" class="form-control @error('form.extraAdultRate') is-invalid @enderror" wire:model="form.extraAdultRate">@error('form.extraAdultRate')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-sm-6 col-lg-3"><label for="rate-extra-child" class="form-label">Extra child</label><input id="rate-extra-child" type="text" inputmode="decimal" class="form-control @error('form.extraChildRate') is-invalid @enderror" wire:model="form.extraChildRate">@error('form.extraChildRate')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-sm-6 col-lg-3"><label for="rate-min-units" class="form-label">Minimum units</label><input id="rate-min-units" type="number" min="1" class="form-control @error('form.minimumUnits') is-invalid @enderror" wire:model="form.minimumUnits">@error('form.minimumUnits')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-sm-6 col-lg-3"><label for="rate-max-units" class="form-label">Maximum units</label><input id="rate-max-units" type="number" min="1" class="form-control @error('form.maximumUnits') is-invalid @enderror" wire:model="form.maximumUnits">@error('form.maximumUnits')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-sm-6 col-lg-3"><label for="rate-min-advance" class="form-label">Minimum advance (minutes)</label><input id="rate-min-advance" type="number" min="0" class="form-control @error('form.minimumAdvanceMinutes') is-invalid @enderror" wire:model="form.minimumAdvanceMinutes">@error('form.minimumAdvanceMinutes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-sm-6 col-lg-3"><label for="rate-max-advance" class="form-label">Maximum advance (days)</label><input id="rate-max-advance" type="number" min="1" class="form-control @error('form.maximumAdvanceDays') is-invalid @enderror" wire:model="form.maximumAdvanceDays">@error('form.maximumAdvanceDays')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                </div></fieldset>
                <fieldset class="pb-form-section"><legend>Tax, deposit, and cancellation</legend><div class="row g-3">
                    <div class="col-md-4"><label for="rate-tax" class="form-label">Tax rate (%)</label><input id="rate-tax" type="text" inputmode="decimal" class="form-control @error('form.taxRatePercent') is-invalid @enderror" wire:model="form.taxRatePercent">@error('form.taxRatePercent')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input id="rate-tax-inclusive" type="checkbox" class="form-check-input" wire:model="form.isTaxInclusive"><label for="rate-tax-inclusive" class="form-check-label">Tax inclusive</label></div></div>
                    <div class="col-md-4"><label for="rate-deposit-type" class="form-label">Deposit type</label><select id="rate-deposit-type" class="form-select @error('form.depositType') is-invalid @enderror" wire:model.live="form.depositType">@foreach($this->depositTypes as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</select>@error('form.depositType')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    @if($form->depositType === \App\Modules\PropertyBooking\Pricing\Enums\DepositType::Fixed->value)<div class="col-md-4"><label for="rate-deposit-amount" class="form-label">Fixed deposit</label><input id="rate-deposit-amount" type="text" inputmode="decimal" class="form-control @error('form.depositAmount') is-invalid @enderror" wire:model="form.depositAmount">@error('form.depositAmount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endif
                    @if($form->depositType === \App\Modules\PropertyBooking\Pricing\Enums\DepositType::Percentage->value)<div class="col-md-4"><label for="rate-deposit-percent" class="form-label">Deposit (%)</label><input id="rate-deposit-percent" type="text" inputmode="decimal" class="form-control @error('form.depositRatePercent') is-invalid @enderror" wire:model="form.depositRatePercent">@error('form.depositRatePercent')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endif
                    <div class="col-md-4"><label for="rate-free-cancel" class="form-label">Free-cancel cutoff (minutes)</label><input id="rate-free-cancel" type="number" min="0" class="form-control @error('form.freeCancelBeforeMinutes') is-invalid @enderror" wire:model="form.freeCancelBeforeMinutes">@error('form.freeCancelBeforeMinutes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    <div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input id="rate-refundable" type="checkbox" class="form-check-input" wire:model="form.isRefundable"><label for="rate-refundable" class="form-check-label">Refundable</label></div></div>
                    <div class="col-12"><label for="rate-cancel-terms" class="form-label">Cancellation terms</label><textarea id="rate-cancel-terms" rows="3" class="form-control @error('form.cancellationTerms') is-invalid @enderror" wire:model="form.cancellationTerms"></textarea>@error('form.cancellationTerms')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                </div></fieldset>
                <fieldset class="pb-form-section"><legend>Visibility</legend><div class="row g-3 align-items-end"><div class="col-md-4"><label for="rate-sort" class="form-label">Sort order</label><input id="rate-sort" type="number" min="0" class="form-control @error('form.sortOrder') is-invalid @enderror" wire:model="form.sortOrder">@error('form.sortOrder')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4"><div class="form-check form-switch mb-2"><input id="rate-public" type="checkbox" class="form-check-input" wire:model="form.isPublic"><label for="rate-public" class="form-check-label">Publicly eligible</label></div></div></div></fieldset>
            </div>
            <div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">{{ $editing ? 'Save changes' : 'Create rate plan' }}</span><span wire:loading wire:target="save">Saving...</span></button></div>
        </form></div></div><div class="modal-backdrop fade show"></div>
    @endif
</div>
