<div id="property-booking-rate-override-manager" class="pb-workspace">
    @php($stats = $this->statistics)
    @include('property-booking::livewire.admin.partials.stat-grid', ['cards' => [
        ['label' => 'Overrides', 'value' => $stats['total'], 'icon' => 'ti-calendar-dollar', 'color' => 'var(--aureon-primary)'],
        ['label' => 'Current and future', 'value' => $stats['future'], 'icon' => 'ti-calendar-forward', 'color' => '#2c6e93'],
        ['label' => 'Closed intervals', 'value' => $stats['closures'], 'icon' => 'ti-calendar-off', 'color' => '#a64242'],
    ]])
    @if(session('success'))<div class="alert alert-success alert-dismissible fade show" role="status">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>@endif
    @error('management')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror

    <section class="card aureon-panel aureon-table-panel" aria-labelledby="rate-override-title">
        <div class="card-header d-flex align-items-center justify-content-between gap-3 flex-wrap"><div><h3 id="rate-override-title" class="card-title mb-1">Date overrides</h3><p class="aureon-muted fs-12 mb-0">Half-open local-date prices and restrictions</p></div>@can(\App\Modules\PropertyBooking\Support\PropertyBookingPermission::MANAGE_RATES)<button type="button" class="btn btn-primary" wire:click="openCreate" @disabled($this->ratePlanOptions->isEmpty())><i class="ti ti-calendar-plus me-2"></i>Add override</button>@endcan</div>
        <div class="pb-filterbar pb-filterbar--compact"><div><label for="override-rate-filter" class="visually-hidden">Rate plan</label><select id="override-rate-filter" class="form-select" wire:model.live="ratePlanFilter"><option value="">All rate plans</option>@foreach($this->ratePlanOptions as $rate)<option value="{{ $rate->id }}">{{ $rate->property->name }} · {{ $rate->name }}</option>@endforeach</select></div><button type="button" class="btn btn-outline-secondary" wire:click="clearFilters"><i class="ti ti-filter-off me-2"></i>Clear</button></div>
        <div class="table-responsive"><table class="table table-hover align-middle mb-0 pb-table"><thead><tr><th>Rate plan</th><th>Dates</th><th>Rate</th><th>Restrictions</th><th>Reason</th><th class="text-end">Actions</th></tr></thead><tbody>
            @forelse($this->overrides as $override)
                <tr wire:key="rate-override-{{ $override->id }}"><td><strong class="d-block">{{ $override->ratePlan->name }}</strong><small class="aureon-muted">{{ $override->ratePlan->property->name }} · {{ $override->ratePlan->unitType->name }}</small></td><td><time datetime="{{ $override->starts_on->toDateString() }}">{{ $override->starts_on->format('d M Y') }}</time><span class="mx-1">→</span><time datetime="{{ $override->ends_on->toDateString() }}">{{ $override->ends_on->format('d M Y') }}</time></td><td><strong>{{ $this->money($override->rate_minor, $override->ratePlan->currency) }}</strong></td><td><div class="d-flex flex-wrap gap-1">@if($override->is_closed)<span class="pb-badge pb-badge--danger">Closed</span>@endif @if($override->closed_on_arrival)<span class="pb-badge pb-badge--warning">No arrival</span>@endif @if($override->closed_on_departure)<span class="pb-badge pb-badge--warning">No departure</span>@endif @if(!$override->is_closed && !$override->closed_on_arrival && !$override->closed_on_departure)<span class="pb-badge pb-badge--success">Open</span>@endif</div><small class="aureon-muted">{{ $override->minimum_units ?? 'Base' }}–{{ $override->maximum_units ?? 'Base' }} units</small></td><td>{{ $override->reason ?: '—' }}</td><td class="text-end text-nowrap">@can('update', $override)<button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openEdit({{ $override->id }})" title="Edit override" aria-label="Edit override"><i class="ti ti-edit"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="delete({{ $override->id }})" wire:confirm="Delete this rate override?" title="Delete override" aria-label="Delete override"><i class="ti ti-trash"></i></button>@endcan</td></tr>
            @empty<tr><td colspan="6"><div class="pb-empty"><i class="ti ti-calendar-off"></i><strong>No rate overrides match this view</strong></div></td></tr>@endforelse
        </tbody></table></div>
        @if($this->overrides->hasPages())<div class="card-footer">{{ $this->overrides->links() }}</div>@endif
    </section>

    @if($dialog === 'form')
        @php($editing = $selectedOverrideId !== null)
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="override-form-title" wire:keydown.escape.window="closeDialog"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><form class="modal-content" wire:submit="save"><div class="modal-header"><div><h3 id="override-form-title" class="modal-title fs-18">{{ $editing ? 'Edit rate override' : 'Create rate override' }}</h3><p class="aureon-muted fs-12 mb-0">Inclusive start and exclusive end dates</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close override form"></button></div><div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror<div class="row g-3">
            <div class="col-12"><label for="override-plan" class="form-label">Rate plan <span class="text-danger">*</span></label><select id="override-plan" class="form-select @error('targetRatePlanId') is-invalid @enderror" wire:model="targetRatePlanId" @disabled($editing)><option value="">Select rate plan</option>@foreach($this->ratePlanOptions as $rate)<option value="{{ $rate->id }}">{{ $rate->property->name }} · {{ $rate->unitType->name }} · {{ $rate->name }}</option>@endforeach</select>@error('targetRatePlanId')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label for="override-start" class="form-label">Starts on <span class="text-danger">*</span></label><input id="override-start" type="date" class="form-control @error('form.startsOn') is-invalid @enderror" wire:model="form.startsOn">@error('form.startsOn')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label for="override-end" class="form-label">Ends on <span class="text-danger">*</span></label><input id="override-end" type="date" class="form-control @error('form.endsOn') is-invalid @enderror" wire:model="form.endsOn">@error('form.endsOn')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label for="override-rate" class="form-label">Replacement rate</label><input id="override-rate" type="text" inputmode="decimal" class="form-control @error('form.rate') is-invalid @enderror" wire:model="form.rate">@error('form.rate')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label for="override-min" class="form-label">Minimum units</label><input id="override-min" type="number" min="1" class="form-control @error('form.minimumUnits') is-invalid @enderror" wire:model="form.minimumUnits">@error('form.minimumUnits')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label for="override-max" class="form-label">Maximum units</label><input id="override-max" type="number" min="1" class="form-control @error('form.maximumUnits') is-invalid @enderror" wire:model="form.maximumUnits">@error('form.maximumUnits')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-sm-4"><div class="form-check form-switch"><input id="override-closed" type="checkbox" class="form-check-input" wire:model="form.isClosed"><label for="override-closed" class="form-check-label">Closed</label></div></div><div class="col-sm-4"><div class="form-check form-switch"><input id="override-arrival" type="checkbox" class="form-check-input" wire:model="form.closedOnArrival"><label for="override-arrival" class="form-check-label">Closed on arrival</label></div></div><div class="col-sm-4"><div class="form-check form-switch"><input id="override-departure" type="checkbox" class="form-check-input" wire:model="form.closedOnDeparture"><label for="override-departure" class="form-check-label">Closed on departure</label></div></div>
            <div class="col-12"><label for="override-reason" class="form-label">Reason</label><input id="override-reason" type="text" class="form-control @error('form.reason') is-invalid @enderror" wire:model="form.reason">@error('form.reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        </div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">{{ $editing ? 'Save changes' : 'Create override' }}</span><span wire:loading wire:target="save">Saving...</span></button></div></form></div></div><div class="modal-backdrop fade show"></div>
    @endif
</div>
