<div id="property-booking-unit-type-manager" class="pb-workspace mb-4">
    @php($stats = $this->statistics)
    @include('property-booking::livewire.admin.partials.stat-grid', ['cards' => [
        ['label' => 'Unit types', 'value' => $stats['total'], 'icon' => 'ti-bed', 'color' => 'var(--aureon-primary)'],
        ['label' => 'Published', 'value' => $stats['published'], 'icon' => 'ti-world-check', 'color' => '#2f7d64'],
        ['label' => 'Drafts', 'value' => $stats['draft'], 'icon' => 'ti-file-pencil', 'color' => '#2c6e93'],
        ['label' => 'Featured', 'value' => $stats['featured'], 'icon' => 'ti-star', 'color' => '#9b6a23'],
    ]])

    @if (session('success'))<div class="alert alert-success alert-dismissible fade show" role="status">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>@endif
    @error('management')<div class="alert alert-danger" role="alert">{{ $message }}</div>@enderror

    <section class="card aureon-panel aureon-table-panel" aria-labelledby="unit-type-title">
        <div class="card-header d-flex align-items-center justify-content-between gap-3 flex-wrap"><div><h3 id="unit-type-title" class="card-title mb-1">Sellable unit types</h3><p class="aureon-muted fs-12 mb-0">Public accommodation descriptions and capacity</p></div>@can(\App\Modules\PropertyBooking\Support\PropertyBookingPermission::MANAGE_PROPERTIES)<button type="button" class="btn btn-primary" wire:click="openCreate"><i class="ti ti-bed-filled me-2"></i>Add unit type</button>@endcan</div>
        <div class="pb-filterbar">
            <div class="pb-filterbar__search"><label for="unit-type-search" class="visually-hidden">Search unit types</label><i class="ti ti-search"></i><input id="unit-type-search" type="search" class="form-control" placeholder="Name, code, or slug" wire:model.live.debounce.300ms="search"></div>
            <div><label for="unit-type-property" class="visually-hidden">Property</label><select id="unit-type-property" class="form-select" wire:model.live="propertyFilter"><option value="">All properties</option>@foreach($this->propertyOptions as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select></div>
            <div><label for="unit-type-status" class="visually-hidden">Status</label><select id="unit-type-status" class="form-select" wire:model.live="statusFilter"><option value="">All statuses</option>@foreach($this->statuses as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div>
            <button type="button" class="btn btn-outline-secondary" wire:click="clearFilters"><i class="ti ti-filter-off me-2"></i>Clear</button>
        </div>
        <div class="table-responsive"><table class="table table-hover align-middle mb-0 pb-table pb-table--unit-types">
            <thead><tr><th>Unit type</th><th>Property</th><th>Capacity</th><th>Inventory</th><th>Status</th><th class="text-end">Actions</th></tr></thead>
            <tbody>
                @forelse($this->unitTypes as $unitType)
                    @php($statusClass = match($unitType->status) { \App\Modules\PropertyBooking\Catalog\Enums\UnitTypeStatus::Published => 'pb-badge--success', \App\Modules\PropertyBooking\Catalog\Enums\UnitTypeStatus::Archived => 'pb-badge--neutral', default => 'pb-badge--info' })
                    <tr wire:key="unit-type-{{ $unitType->id }}">
                        <td><div class="d-flex align-items-center gap-3">@if($unitType->getFirstMediaUrl('unit_type_cover', 'thumb'))<img src="{{ $unitType->getFirstMediaUrl('unit_type_cover', 'thumb') }}" alt="{{ $unitType->getFirstMedia('unit_type_cover')?->getCustomProperty('alt_text', '') }}" class="pb-thumb">@else<span class="pb-thumb pb-thumb--placeholder"><i class="ti ti-bed"></i></span>@endif<div class="min-w-0"><strong class="d-block text-break">{{ $unitType->name }}</strong><code class="pb-code">{{ $unitType->code }}</code>@if($unitType->is_featured)<small class="d-block pb-featured mt-1"><i class="ti ti-star-filled"></i> Featured</small>@endif</div></div></td>
                        <td><span class="d-block">{{ $unitType->property->name }}</span><small class="aureon-muted">{{ $unitType->property->code }}</small></td>
                        <td><span class="d-block">{{ number_format($unitType->maximum_guests) }} guests</span><small class="aureon-muted">{{ number_format($unitType->bed_count) }} beds · {{ $unitType->size_square_metres ? $unitType->size_square_metres.' m²' : 'Size pending' }}</small></td>
                        <td><span class="d-block">{{ number_format($unitType->units_count) }} units</span><small class="aureon-muted">{{ number_format($unitType->rate_plans_count) }} rates</small></td>
                        <td><span class="pb-badge {{ $statusClass }}">{{ $unitType->status->label() }}</span></td>
                        <td class="text-end text-nowrap">@can('update', $unitType)<button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openMedia({{ $unitType->id }})" data-bs-toggle="tooltip" title="Manage images" aria-label="Manage images for {{ $unitType->name }}"><i class="ti ti-photo"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openEdit({{ $unitType->id }})" data-bs-toggle="tooltip" title="Edit unit type" aria-label="Edit {{ $unitType->name }}"><i class="ti ti-edit"></i></button><select class="form-select form-select-sm pb-inline-select" aria-label="Change status for {{ $unitType->name }}" wire:change="changeStatus({{ $unitType->id }}, $event.target.value)"><option value="">Status</option>@foreach($this->statuses as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select>@endcan</td>
                    </tr>
                @empty
                    <tr><td colspan="6"><div class="pb-empty"><i class="ti ti-bed-off"></i><strong>No unit types match this view</strong></div></td></tr>
                @endforelse
            </tbody>
        </table></div>
        @if($this->unitTypes->hasPages())<div class="card-footer">{{ $this->unitTypes->links() }}</div>@endif
    </section>

    @if($dialog === 'form')
        @php($editing = $selectedUnitTypeId !== null)
        @php($formUnitType = $this->formUnitType)
        @php($formUnitTypeCover = $formUnitType?->getFirstMedia('unit_type_cover'))
        @php($formUnitTypeGallery = $formUnitType?->getMedia('unit_type_gallery') ?? collect())
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="unit-type-form-title" wire:keydown.escape.window="closeDialog">
            <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><form class="modal-content" wire:submit="save">
                <div class="modal-header"><div><h3 id="unit-type-form-title" class="modal-title fs-18">{{ $editing ? 'Edit unit type' : 'Create unit type' }}</h3><p class="aureon-muted fs-12 mb-0">Description, physical layout, occupancy, and listing metadata</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close unit-type form"></button></div>
                <div class="modal-body">@error('management')<div class="alert alert-danger">{{ $message }}</div>@enderror
                    <fieldset class="pb-form-section"><legend>Identity and content</legend><div class="row g-3">
                        <div class="col-md-4"><label for="type-form-property" class="form-label">Property <span class="text-danger">*</span></label><select id="type-form-property" class="form-select @error('form.propertyId') is-invalid @enderror" wire:model="form.propertyId" @disabled($editing)><option value="">Select property</option>@foreach($this->propertyOptions as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select>@error('form.propertyId')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-4"><label for="type-form-name" class="form-label">Name <span class="text-danger">*</span></label><input id="type-form-name" type="text" class="form-control @error('form.name') is-invalid @enderror" wire:model="form.name">@error('form.name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-4"><label for="type-form-code" class="form-label">Code <span class="text-danger">*</span></label><input id="type-form-code" type="text" class="form-control @error('form.code') is-invalid @enderror" wire:model="form.code">@error('form.code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-6"><label for="type-form-slug" class="form-label">URL slug</label><input id="type-form-slug" type="text" class="form-control @error('form.slug') is-invalid @enderror" wire:model="form.slug" placeholder="Generated from name">@error('form.slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-md-6"><label for="type-form-size" class="form-label">Floor area (m²)</label><input id="type-form-size" type="text" inputmode="decimal" class="form-control @error('form.sizeSquareMetres') is-invalid @enderror" wire:model="form.sizeSquareMetres">@error('form.sizeSquareMetres')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-12"><label for="type-form-short" class="form-label">Short description</label><textarea id="type-form-short" rows="2" class="form-control @error('form.shortDescription') is-invalid @enderror" wire:model="form.shortDescription"></textarea>@error('form.shortDescription')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-12"><label for="type-form-description" class="form-label">Full description</label><textarea id="type-form-description" rows="5" class="form-control @error('form.description') is-invalid @enderror" wire:model="form.description"></textarea>@error('form.description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                    </div></fieldset>
                    <fieldset class="pb-form-section pb-form-media-editor"><legend>Unit photography</legend>
                        <div class="pb-form-media-canvas mb-3">
                            @if($formCoverUpload)
                                <img src="{{ $formCoverUpload->temporaryUrl() }}" alt="New unit-type cover preview">
                                <span class="pb-form-media-canvas__label">New cover</span>
                            @elseif($formUnitTypeCover)
                                <img src="{{ $formUnitTypeCover->getUrl('detail') }}" alt="{{ $formUnitTypeCover->getCustomProperty('alt_text', '') }}">
                                <span class="pb-form-media-canvas__label">Current cover</span>
                            @else
                                <div class="pb-form-media-placeholder"><i class="ti ti-photo-plus" aria-hidden="true"></i><strong>Unit-type cover</strong><small>Show the room or apartment clearly</small></div>
                            @endif
                        </div>
                        <div class="row g-3 mb-4">
                            <div class="col-lg-4"><label for="type-form-cover" class="form-label">Cover image</label><input id="type-form-cover" type="file" accept="image/jpeg,image/png,image/webp" class="form-control @error('formCoverUpload') is-invalid @enderror" wire:model="formCoverUpload">@error('formCoverUpload')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                            <div class="col-lg-4"><label for="type-form-cover-alt" class="form-label">Cover alternative text</label><input id="type-form-cover-alt" type="text" class="form-control @error('formCoverAltText') is-invalid @enderror" wire:model="formCoverAltText" placeholder="Describe what the image shows">@error('formCoverAltText')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                            <div class="col-lg-4"><label for="type-form-cover-caption" class="form-label">Cover caption</label><input id="type-form-cover-caption" type="text" class="form-control @error('formCoverCaption') is-invalid @enderror" wire:model="formCoverCaption" placeholder="Optional guest-facing caption">@error('formCoverCaption')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        </div>
                        <div class="pb-section-heading"><div><h4>Gallery additions</h4><small>Concrete room numbers inherit this sellable unit-type gallery.</small></div><span class="pb-badge pb-badge--neutral">{{ number_format($formUnitTypeGallery->count()) }} current</span></div>
                        <div class="mb-3"><label for="type-form-gallery" class="form-label">Gallery images</label><input id="type-form-gallery" type="file" multiple accept="image/jpeg,image/png,image/webp" class="form-control @error('formGalleryUploads') is-invalid @enderror @error('formGalleryUploads.*') is-invalid @enderror" wire:model="formGalleryUploads">@error('formGalleryUploads')<div class="invalid-feedback">{{ $message }}</div>@enderror @error('formGalleryUploads.*')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        @if($formGalleryUploads !== [])
                            <div class="pb-form-gallery-editor mb-3">
                                @foreach($formGalleryUploads as $index => $upload)
                                    <article class="pb-form-gallery-editor__item" wire:key="type-form-gallery-{{ $index }}">
                                        <img src="{{ $upload->temporaryUrl() }}" alt="New unit gallery image {{ $index + 1 }} preview">
                                        <div class="pb-form-gallery-editor__fields">
                                            <label for="type-form-gallery-alt-{{ $index }}" class="form-label">Alternative text <span class="text-danger">*</span></label>
                                            <input id="type-form-gallery-alt-{{ $index }}" type="text" class="form-control @error('formGalleryAltTexts.'.$index) is-invalid @enderror" wire:model="formGalleryAltTexts.{{ $index }}">
                                            @error('formGalleryAltTexts.'.$index)<div class="invalid-feedback">{{ $message }}</div>@enderror
                                            <label for="type-form-gallery-caption-{{ $index }}" class="form-label mt-2">Caption</label>
                                            <input id="type-form-gallery-caption-{{ $index }}" type="text" class="form-control @error('formGalleryCaptions.'.$index) is-invalid @enderror" wire:model="formGalleryCaptions.{{ $index }}">
                                            @error('formGalleryCaptions.'.$index)<div class="invalid-feedback">{{ $message }}</div>@enderror
                                        </div>
                                    </article>
                                @endforeach
                            </div>
                        @elseif($formUnitTypeGallery->isNotEmpty())
                            <div class="pb-form-gallery-existing mb-3" aria-label="Current unit-type gallery">
                                @foreach($formUnitTypeGallery as $image)<img src="{{ $image->getUrl('thumb') }}" alt="{{ $image->getCustomProperty('alt_text', '') }}">@endforeach
                            </div>
                        @endif
                    </fieldset>
                    <fieldset class="pb-form-section"><legend>Physical layout and occupancy</legend><div class="row g-3">
                        <div class="col-6 col-lg-3"><label for="type-bedrooms" class="form-label">Bedrooms</label><input id="type-bedrooms" type="number" min="0" class="form-control @error('form.bedroomCount') is-invalid @enderror" wire:model="form.bedroomCount">@error('form.bedroomCount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-lg-3"><label for="type-bathrooms" class="form-label">Bathrooms</label><input id="type-bathrooms" type="number" min="0" class="form-control @error('form.bathroomCount') is-invalid @enderror" wire:model="form.bathroomCount">@error('form.bathroomCount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-lg-3"><label for="type-living" class="form-label">Living rooms</label><input id="type-living" type="number" min="0" class="form-control @error('form.livingRoomCount') is-invalid @enderror" wire:model="form.livingRoomCount">@error('form.livingRoomCount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-lg-3"><label for="type-beds" class="form-label">Beds</label><input id="type-beds" type="number" min="0" class="form-control @error('form.bedCount') is-invalid @enderror" wire:model="form.bedCount">@error('form.bedCount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-12"><label for="type-bed-config" class="form-label">Bed configuration (JSON)</label><textarea id="type-bed-config" rows="4" class="form-control font-monospace @error('form.bedConfigurationJson') is-invalid @enderror" wire:model="form.bedConfigurationJson"></textarea>@error('form.bedConfigurationJson')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-lg-3"><label for="type-max-guests" class="form-label">Maximum guests</label><input id="type-max-guests" type="number" min="1" class="form-control @error('form.maximumGuests') is-invalid @enderror" wire:model="form.maximumGuests">@error('form.maximumGuests')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-lg-3"><label for="type-max-adults" class="form-label">Maximum adults</label><input id="type-max-adults" type="number" min="1" class="form-control @error('form.maximumAdults') is-invalid @enderror" wire:model="form.maximumAdults">@error('form.maximumAdults')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-lg-3"><label for="type-max-children" class="form-label">Maximum children</label><input id="type-max-children" type="number" min="0" class="form-control @error('form.maximumChildren') is-invalid @enderror" wire:model="form.maximumChildren">@error('form.maximumChildren')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-6 col-lg-3"><label for="type-max-infants" class="form-label">Maximum infants</label><input id="type-max-infants" type="number" min="0" class="form-control @error('form.maximumInfants') is-invalid @enderror" wire:model="form.maximumInfants">@error('form.maximumInfants')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-sm-6 col-lg-3"><div class="form-check form-switch"><input id="type-infants-top" type="checkbox" class="form-check-input" wire:model="form.allowsInfantsOnTop"><label for="type-infants-top" class="form-check-label">Infants above guest cap</label></div></div>
                        <div class="col-sm-6 col-lg-3"><div class="form-check form-switch"><input id="type-entire" type="checkbox" class="form-check-input" wire:model="form.isEntireUnit"><label for="type-entire" class="form-check-label">Entire unit</label></div></div>
                        <div class="col-sm-6 col-lg-3"><div class="form-check form-switch"><input id="type-smoking" type="checkbox" class="form-check-input" wire:model="form.smokingAllowed"><label for="type-smoking" class="form-check-label">Smoking allowed</label></div></div>
                        <div class="col-sm-6 col-lg-3"><div class="form-check form-switch"><input id="type-featured" type="checkbox" class="form-check-input" wire:model="form.isFeatured"><label for="type-featured" class="form-check-label">Featured</label></div></div>
                    </div></fieldset>
                    <fieldset class="pb-form-section"><legend>Amenities and discovery</legend><div class="row g-3">
                        <div class="col-lg-5"><label for="type-amenities" class="form-label">Unit-type amenities</label><select id="type-amenities" class="form-select @error('form.amenityIds') is-invalid @enderror" multiple size="7" wire:model="form.amenityIds">@foreach($this->amenityOptions as $amenity)<option value="{{ $amenity->id }}">{{ $amenity->name }}</option>@endforeach</select>@error('form.amenityIds')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="col-lg-7"><div class="row g-3"><div class="col-12"><label for="type-meta-title" class="form-label">Meta title</label><input id="type-meta-title" type="text" class="form-control @error('form.metaTitle') is-invalid @enderror" wire:model="form.metaTitle">@error('form.metaTitle')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label for="type-meta-description" class="form-label">Meta description</label><textarea id="type-meta-description" rows="4" class="form-control @error('form.metaDescription') is-invalid @enderror" wire:model="form.metaDescription"></textarea>@error('form.metaDescription')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
                    </div></fieldset>
                </div>
                <div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeDialog">Cancel</button><button type="submit" class="btn btn-primary" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">{{ $editing ? 'Save changes' : 'Create unit type' }}</span><span wire:loading wire:target="save">Saving...</span></button></div>
            </form></div>
        </div><div class="modal-backdrop fade show"></div>
    @elseif($dialog === 'media' && $this->mediaUnitType)
        @php($mediaType = $this->mediaUnitType)
        @php($cover = $mediaType->getFirstMedia('unit_type_cover'))
        @php($gallery = $mediaType->getMedia('unit_type_gallery'))
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="type-media-title" wire:keydown.escape.window="closeDialog"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
            <div class="modal-header"><div><h3 id="type-media-title" class="modal-title fs-18">{{ $mediaType->name }} media</h3><p class="aureon-muted fs-12 mb-0">Cover and ordered gallery</p></div><button type="button" class="btn-close" wire:click="closeDialog" aria-label="Close media workspace"></button></div>
            <div class="modal-body">@error('media')<div class="alert alert-danger">{{ $message }}</div>@enderror
                <section class="pb-media-section"><div class="pb-section-heading"><div><h4>Cover image</h4><small>{{ $cover ? 'Configured' : 'Not configured' }}</small></div>@if($cover)<div class="d-flex gap-1"><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openMediaMetadata({{ $cover->id }})" title="Edit metadata"><i class="ti ti-edit"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="removeCover" wire:confirm="Remove this cover image?" title="Remove cover"><i class="ti ti-trash"></i></button></div>@endif</div><div class="row g-3">@if($cover)<div class="col-lg-4"><img src="{{ $cover->getUrl('card') }}" alt="{{ $cover->getCustomProperty('alt_text', '') }}" class="pb-media-cover"></div>@endif<div class="{{ $cover ? 'col-lg-8' : 'col-12' }}"><form wire:submit="replaceCover" class="row g-3"><div class="col-md-6"><label for="type-cover-file" class="form-label">Image</label><input id="type-cover-file" type="file" accept="image/jpeg,image/png,image/webp" class="form-control @error('coverUpload') is-invalid @enderror" wire:model="coverUpload">@error('coverUpload')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label for="type-cover-alt" class="form-label">Alternative text</label><input id="type-cover-alt" type="text" class="form-control @error('mediaAltText') is-invalid @enderror" wire:model="mediaAltText">@error('mediaAltText')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-9"><label for="type-cover-caption" class="form-label">Caption</label><input id="type-cover-caption" type="text" class="form-control @error('mediaCaption') is-invalid @enderror" wire:model="mediaCaption">@error('mediaCaption')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-3 d-flex align-items-end"><button type="submit" class="btn btn-primary w-100">Replace cover</button></div></form></div></div></section>
                <section class="pb-media-section"><div class="pb-section-heading"><div><h4>Gallery</h4><small>{{ number_format($gallery->count()) }} / {{ number_format(config('property-booking.media.unit_type_gallery_limit', 10)) }} images</small></div></div><form wire:submit="addGalleryImage" class="row g-3 mb-4"><div class="col-md-4"><label for="type-gallery-file" class="form-label">Image</label><input id="type-gallery-file" type="file" accept="image/jpeg,image/png,image/webp" class="form-control @error('galleryUpload') is-invalid @enderror" wire:model="galleryUpload">@error('galleryUpload')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4"><label for="type-gallery-alt" class="form-label">Alternative text</label><input id="type-gallery-alt" type="text" class="form-control @error('mediaAltText') is-invalid @enderror" wire:model="mediaAltText">@error('mediaAltText')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-3"><label for="type-gallery-caption" class="form-label">Caption</label><input id="type-gallery-caption" type="text" class="form-control @error('mediaCaption') is-invalid @enderror" wire:model="mediaCaption">@error('mediaCaption')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-1 d-flex align-items-end"><button type="submit" class="btn btn-icon btn-primary" title="Add gallery image"><i class="ti ti-plus"></i></button></div></form>
                    <div class="pb-gallery-grid">@forelse($gallery as $image)<article class="pb-gallery-item" wire:key="unit-type-gallery-{{ $image->id }}"><img src="{{ $image->getUrl('thumb') }}" alt="{{ $image->getCustomProperty('alt_text', '') }}"><div class="pb-gallery-item__copy"><strong>{{ $image->getCustomProperty('alt_text', 'Image') }}</strong><small>{{ $image->getCustomProperty('caption', '') }}</small></div><div class="pb-gallery-item__actions"><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="moveGalleryImage({{ $image->id }}, 'up')" title="Move earlier"><i class="ti ti-arrow-left"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="moveGalleryImage({{ $image->id }}, 'down')" title="Move later"><i class="ti ti-arrow-right"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-secondary" wire:click="openMediaMetadata({{ $image->id }})" title="Edit metadata"><i class="ti ti-edit"></i></button><button type="button" class="btn btn-icon btn-sm btn-outline-danger" wire:click="removeGalleryImage({{ $image->id }})" wire:confirm="Remove this gallery image?" title="Remove image"><i class="ti ti-trash"></i></button></div></article>@empty<div class="pb-empty"><i class="ti ti-photo-off"></i><strong>No gallery images</strong></div>@endforelse</div>
                </section>
            </div><div class="modal-footer"><button type="button" class="btn btn-primary" wire:click="closeDialog">Done</button></div>
        </div></div></div><div class="modal-backdrop fade show"></div>
    @elseif($dialog === 'metadata')
        <div class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="type-metadata-title" wire:keydown.escape.window="closeMetadata"><div class="modal-dialog modal-md modal-dialog-centered"><form class="modal-content" wire:submit="saveMediaMetadata"><div class="modal-header"><h3 id="type-metadata-title" class="modal-title fs-18">Image metadata</h3><button type="button" class="btn-close" wire:click="closeMetadata" aria-label="Close metadata form"></button></div><div class="modal-body"><div class="mb-3"><label for="type-media-alt" class="form-label">Alternative text <span class="text-danger">*</span></label><input id="type-media-alt" type="text" class="form-control @error('mediaAltText') is-invalid @enderror" wire:model="mediaAltText">@error('mediaAltText')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label for="type-media-caption" class="form-label">Caption</label><textarea id="type-media-caption" rows="3" class="form-control @error('mediaCaption') is-invalid @enderror" wire:model="mediaCaption"></textarea>@error('mediaCaption')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" wire:click="closeMetadata">Cancel</button><button type="submit" class="btn btn-primary">Save metadata</button></div></form></div></div><div class="modal-backdrop fade show"></div>
    @endif
</div>
