@php
    $accountUrl = auth()->check() ? route('dashboard') : route('login');
    $accountLabel = auth()->check() ? 'Workspace' : 'Account';
@endphp
<header class="pb-storefront-header" data-pb-header>
    <div class="pb-storefront-desktop d-none d-xl-block">
        <div class="pb-storefront-utility"><div class="container-xxl"><p><i data-lucide="calendar-check" aria-hidden="true"></i> Direct availability. Clear local pricing.</p><nav aria-label="Stay utility navigation"><span>{{ config('property-booking.defaults.currency', 'KES') }}</span><span><i data-lucide="shield-check" aria-hidden="true"></i> Secure booking</span>@if($profile->primaryPhone)<a href="tel:{{ preg_replace('/[^+\d]/', '', $profile->primaryPhone) }}">{{ $profile->primaryPhone }}</a>@endif</nav></div></div>
        <div class="pb-storefront-primary"><div class="container-xxl pb-storefront-primary__grid">
            <nav class="pb-storefront-primary__nav" aria-label="Primary stay navigation"><a class="{{ request()->routeIs('property-booking.storefront.catalog.*', 'property-booking.storefront.properties.*', 'property-booking.storefront.units.*') ? 'active' : '' }}" href="{{ route('property-booking.storefront.catalog.index') }}">Discover</a><a href="{{ route('property-booking.storefront.catalog.index') }}#stay-search">Find a stay</a></nav>
            <a class="pb-storefront-brand" href="{{ route('property-booking.storefront.catalog.index') }}" aria-label="{{ $profile->name }} stays home"><img class="pb-storefront-brand__default" src="{{ $brandLogo }}" alt="{{ $profile->name }}" width="220" height="64"><img class="pb-storefront-brand__dark" src="{{ $brandLogoLight }}" alt="" width="220" height="64" aria-hidden="true"><span>Stays</span></a>
            <nav class="pb-storefront-primary__tools" aria-label="Stay tools"><a class="pb-storefront-icon-button" href="{{ route('property-booking.storefront.catalog.index') }}#stay-search" aria-label="Search accommodation" title="Search accommodation"><i data-lucide="search" aria-hidden="true"></i></a><a class="pb-storefront-icon-button" href="{{ $accountUrl }}" aria-label="{{ $accountLabel }}" title="{{ $accountLabel }}"><i data-lucide="user-round" aria-hidden="true"></i></a><button class="pb-storefront-icon-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#themeController" aria-controls="themeController" aria-label="Open theme settings" title="Theme settings"><i data-lucide="palette" aria-hidden="true"></i></button></nav>
        </div></div>
        @if($navigationCategories->isNotEmpty())<nav class="pb-storefront-category-bar" aria-label="Accommodation categories"><div class="container-xxl">@foreach($navigationCategories as $category)<a href="{{ route('property-booking.storefront.catalog.index', ['category' => $category->slug]) }}">{{ $category->name }} <span>{{ $category->published_properties_count }}</span></a>@endforeach</div></nav>@endif
    </div>
    <div class="pb-storefront-compact d-none d-md-grid d-xl-none"><button class="pb-storefront-icon-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#pbMobileMenu" aria-controls="pbMobileMenu" aria-label="Open navigation" title="Menu"><i data-lucide="menu" aria-hidden="true"></i></button><a class="pb-storefront-brand" href="{{ route('property-booking.storefront.catalog.index') }}"><img class="pb-storefront-brand__default" src="{{ $brandLogo }}" alt="{{ $profile->name }}" width="220" height="64"><img class="pb-storefront-brand__dark" src="{{ $brandLogoLight }}" alt="" width="220" height="64" aria-hidden="true"><span>Stays</span></a><div class="pb-storefront-compact__tools"><a class="pb-storefront-icon-button" href="{{ $accountUrl }}" aria-label="{{ $accountLabel }}" title="{{ $accountLabel }}"><i data-lucide="user-round" aria-hidden="true"></i></a><button class="pb-storefront-icon-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#themeController" aria-label="Open theme settings" title="Theme settings"><i data-lucide="palette" aria-hidden="true"></i></button></div></div>
    <div class="pb-storefront-mobile d-grid d-md-none"><button class="pb-storefront-icon-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#pbMobileMenu" aria-controls="pbMobileMenu" aria-label="Open navigation" title="Menu"><i data-lucide="menu" aria-hidden="true"></i></button><a class="pb-storefront-brand" href="{{ route('property-booking.storefront.catalog.index') }}"><img class="pb-storefront-brand__default" src="{{ $brandLogo }}" alt="{{ $profile->name }}" width="180" height="52"><img class="pb-storefront-brand__dark" src="{{ $brandLogoLight }}" alt="" width="180" height="52" aria-hidden="true"><span>Stays</span></a><button class="pb-storefront-icon-button" type="button" data-bs-toggle="offcanvas" data-bs-target="#themeController" aria-label="Open theme settings" title="Theme settings"><i data-lucide="palette" aria-hidden="true"></i></button></div>
</header>
<aside class="offcanvas offcanvas-start pb-storefront-menu" tabindex="-1" id="pbMobileMenu" aria-labelledby="pbMobileMenuTitle"><div class="offcanvas-header"><a class="pb-storefront-brand" href="{{ route('property-booking.storefront.catalog.index') }}" id="pbMobileMenuTitle"><img class="pb-storefront-brand__default" src="{{ $brandLogo }}" alt="{{ $profile->name }}" width="190" height="58"><img class="pb-storefront-brand__dark" src="{{ $brandLogoLight }}" alt="" width="190" height="58" aria-hidden="true"><span>Stays</span></a><button class="pb-storefront-icon-button" type="button" data-bs-dismiss="offcanvas" aria-label="Close navigation" title="Close"><i data-lucide="x" aria-hidden="true"></i></button></div><div class="offcanvas-body"><nav aria-label="Mobile stay navigation"><a href="{{ route('property-booking.storefront.catalog.index') }}">Discover stays <i data-lucide="arrow-up-right" aria-hidden="true"></i></a><a href="{{ route('property-booking.storefront.catalog.index') }}#stay-search">Check availability <i data-lucide="calendar-search" aria-hidden="true"></i></a>@if($navigationCategories->isNotEmpty())<div class="pb-storefront-menu__group"><button type="button" data-bs-toggle="collapse" data-bs-target="#pbMobileCategories" aria-expanded="true"><span>Stay types</span><i data-lucide="chevron-down" aria-hidden="true"></i></button><div class="collapse show" id="pbMobileCategories">@foreach($navigationCategories as $category)<a href="{{ route('property-booking.storefront.catalog.index', ['category' => $category->slug]) }}"><span>{{ $category->name }}</span><small>{{ $category->published_properties_count }}</small></a>@endforeach</div></div>@endif<a href="{{ $accountUrl }}">{{ $accountLabel }} <i data-lucide="user-round" aria-hidden="true"></i></a></nav><div class="pb-storefront-menu__contact">@if($profile->primaryEmail)<a href="mailto:{{ $profile->primaryEmail }}">{{ $profile->primaryEmail }}</a>@endif @if($profile->primaryPhone)<a href="tel:{{ preg_replace('/[^+\d]/', '', $profile->primaryPhone) }}">{{ $profile->primaryPhone }}</a>@endif @if($profile->address())<p>{{ $profile->address() }}</p>@endif</div></div></aside>
