@extends('property-booking::layouts.storefront')

@section('title', $property->meta_title ?: $property->name)
@section('meta_description', $property->meta_description ?: $property->short_description)
@section('social_image', $property->getFirstMediaUrl('property_cover', 'detail') ?: asset('aureon/assets/brand/twitter-card.png'))
@section('og_type', 'website')

@section('content')
    <section class="pb-stay-detail"><div class="container-xxl"><nav class="pb-stay-breadcrumb" aria-label="Breadcrumb"><a href="{{ route('property-booking.storefront.catalog.index') }}">Stays</a><i data-lucide="chevron-right" aria-hidden="true"></i><span>{{ $property->name }}</span></nav>@include('property-booking::storefront.partials.gallery', ['galleryModel' => $property, 'coverCollection' => 'property_cover', 'galleryCollection' => 'property_gallery', 'galleryLabel' => $property->name])
        <div class="pb-stay-detail__intro"><div><p class="pb-storefront-eyebrow">{{ $property->category?->name }} @if($property->is_featured)<span>Featured</span>@endif</p><h1>{{ $property->name }}</h1><p class="pb-stay-detail__lead">{{ $property->short_description }}</p><div class="pb-stay-detail__location"><i data-lucide="map-pin" aria-hidden="true"></i><span>{{ collect([$property->address_line_1, $property->city, $property->region, $property->country_code])->filter()->implode(', ') }}</span></div></div><dl class="pb-stay-detail__times"><div><dt>Check in</dt><dd>{{ substr((string) $property->check_in_from, 0, 5) }}</dd></div><div><dt>Check out</dt><dd>{{ substr((string) $property->check_out_until, 0, 5) }}</dd></div><div><dt>Local time</dt><dd>{{ $property->timezone }}</dd></div></dl></div>
    </div></section>
    <section class="pb-stay-content-band"><div class="container-xxl pb-stay-content-grid"><article><h2>About this property</h2><div class="pb-stay-rich-copy">{!! nl2br(e($property->description)) !!}</div>@if($property->amenities->isNotEmpty())<h2>Amenities</h2><ul class="pb-stay-amenities">@foreach($property->amenities as $amenity)<li><i data-lucide="check" aria-hidden="true"></i><span><strong>{{ $amenity->name }}</strong>@if($amenity->pivot?->detail)<small>{{ $amenity->pivot->detail }}</small>@endif</span></li>@endforeach</ul>@endif</article><aside>@if($property->house_rules)<section><h2>House rules</h2><p>{{ $property->house_rules }}</p></section>@endif @if($property->cancellation_summary)<section><h2>Cancellation</h2><p>{{ $property->cancellation_summary }}</p></section>@endif</aside></div></section>
    <section class="pb-stay-units"><div class="container-xxl"><div class="pb-stay-section-heading"><div><p class="pb-storefront-eyebrow">Accommodation</p><h2>Choose your space</h2></div><p>Unit identities remain private until the operations team assigns your stay.</p></div><div class="pb-stay-unit-grid">@foreach($property->unitTypes as $unitType)@php($cover = $unitType->getFirstMedia('unit_type_cover'))<article class="pb-stay-unit-card"><a href="{{ route('property-booking.storefront.units.show', ['property' => $property->slug, 'unitType' => $unitType->slug] + request()->only(['arrival','departure','arrival_time','departure_time','adults','children','infants'])) }}">@if($cover)<img src="{{ $cover->getUrl('card') }}" alt="{{ $cover->getCustomProperty('alt_text', $unitType->name) }}" width="720" height="540" loading="lazy">@else<span class="pb-stay-unit-card__placeholder"><i data-lucide="bed-double" aria-hidden="true"></i></span>@endif</a><div><p>{{ $unitType->is_entire_unit ? 'Entire unit' : 'Private accommodation' }}</p><h3><a href="{{ route('property-booking.storefront.units.show', ['property' => $property->slug, 'unitType' => $unitType->slug] + request()->only(['arrival','departure','arrival_time','departure_time','adults','children','infants'])) }}">{{ $unitType->name }}</a></h3><p>{{ $unitType->short_description }}</p><ul><li><i data-lucide="users" aria-hidden="true"></i>Up to {{ $unitType->maximum_guests }} guests</li><li><i data-lucide="bed" aria-hidden="true"></i>{{ $unitType->bed_count }} {{ \Illuminate\Support\Str::plural('bed', $unitType->bed_count) }}</li><li><i data-lucide="ruler" aria-hidden="true"></i>{{ $unitType->size_square_metres }} m2</li></ul><a class="pb-storefront-text-link" href="{{ route('property-booking.storefront.units.show', ['property' => $property->slug, 'unitType' => $unitType->slug] + request()->only(['arrival','departure','arrival_time','departure_time','adults','children','infants'])) }}">View space <i data-lucide="arrow-right" aria-hidden="true"></i></a></div></article>@endforeach</div></div></section>
    <livewire:property-booking.storefront.property-availability :property-id="$property->id" />
@endsection
