<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the unified order aggregate for web checkout and POS sales.
 */
return new class extends Migration
{
    /**
     * Create order headers with customer, pricing, fulfillment, and lifecycle snapshots.
     */
    public function up(): void
    {
        Schema::create('orders', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for order relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid; authorization is enforced separately.');
            $table->string('order_number', 40)->nullable()->unique()->comment('Human-readable business number assigned when an order is placed or completed.');
            $table->string('channel', 20)->comment('Originating transaction surface backed by Orders Enums OrderChannel.');
            $table->string('status', 30)->comment('Fulfillment lifecycle backed by Orders Enums OrderStatus.');
            $table->string('payment_status', 20)->default('unpaid')->comment('Aggregate settlement state backed by Orders Enums OrderPaymentStatus.');
            $table->string('fulfillment_type', 20)->comment('Customer handover mode backed by Orders Enums FulfillmentType.');
            $table->string('preferred_payment_method', 30)->nullable()->comment('Checkout or POS preference backed by Orders Enums PaymentMethod.');
            $table->foreignId('customer_id')->nullable()->comment('Optional reusable customer record linked to this order.')->constrained('customers')->nullOnDelete();
            $table->foreignId('user_id')->nullable()->comment('Optional authenticated storefront account that placed the order.')->constrained('users')->nullOnDelete();
            $table->foreignId('register_id')->nullable()->comment('POS register used for a point-of-sale order.')->constrained('registers')->nullOnDelete();
            $table->foreignId('till_session_id')->nullable()->comment('Open till session responsible for a point-of-sale order.')->constrained('till_sessions')->nullOnDelete();
            $table->foreignId('cashier_id')->nullable()->comment('Cashier who completed a point-of-sale order.')->constrained('users')->nullOnDelete();
            $table->foreignId('created_by')->nullable()->comment('Staff user who created or entered the order when applicable.')->constrained('users')->nullOnDelete();
            $table->char('currency', 3)->comment('ISO 4217 currency code copied onto the order at calculation time.');
            $table->unsignedBigInteger('subtotal_minor')->default(0)->comment('Sum of line subtotals before order discount and delivery in currency minor units.');
            $table->unsignedBigInteger('discount_minor')->default(0)->comment('Fixed discount allocated across order lines in currency minor units.');
            $table->string('discount_reason', 160)->nullable()->comment('Optional staff-readable reason for an order-level discount.');
            $table->unsignedBigInteger('delivery_fee_minor')->default(0)->comment('Configured delivery charge in currency minor units.');
            $table->unsignedBigInteger('tax_minor')->default(0)->comment('Total tax snapshot across all order lines in currency minor units.');
            $table->unsignedBigInteger('total_minor')->default(0)->comment('Final amount payable after discount, tax treatment, and delivery in currency minor units.');
            $table->unsignedBigInteger('paid_minor')->default(0)->comment('Completed payment amount applied to this order in currency minor units.');
            $table->boolean('tax_inclusive')->default(true)->comment('Whether item prices were treated as tax inclusive when totals were calculated.');
            $table->string('customer_first_name', 100)->comment('Immutable customer first-name snapshot used on documents.');
            $table->string('customer_last_name', 100)->comment('Immutable customer last-name snapshot used on documents.');
            $table->string('customer_company', 160)->nullable()->comment('Immutable customer organization snapshot used on documents.');
            $table->string('customer_tax_identifier', 80)->nullable()->comment('Immutable customer tax or business identifier snapshot.');
            $table->string('customer_email', 255)->nullable()->comment('Immutable customer email snapshot used for order communication.');
            $table->string('customer_phone', 40)->nullable()->comment('Immutable customer telephone snapshot used for fulfillment contact.');
            $table->string('address_line_1', 180)->nullable()->comment('Immutable delivery street, building, or address line.');
            $table->string('address_line_2', 180)->nullable()->comment('Optional immutable continuation of the delivery address.');
            $table->string('city', 100)->nullable()->comment('Immutable delivery city or locality.');
            $table->string('region', 100)->nullable()->comment('Immutable delivery county, state, province, or region.');
            $table->string('postal_code', 30)->nullable()->comment('Immutable delivery postal or ZIP code.');
            $table->char('country_code', 2)->default('KE')->comment('Immutable ISO 3166-1 alpha-2 delivery country code.');
            $table->text('customer_note')->nullable()->comment('Customer-provided fulfillment note copied from checkout.');
            $table->text('internal_note')->nullable()->comment('Staff-only operational note never rendered publicly.');
            $table->string('cancellation_reason', 255)->nullable()->comment('Staff or customer-safe reason recorded when an eligible order is cancelled.');
            $table->timestamp('stock_committed_at')->nullable()->comment('Timestamp when order quantities were atomically deducted from stock.');
            $table->timestamp('stock_released_at')->nullable()->comment('Timestamp when a cancellation atomically restored committed stock.');
            $table->timestamp('placed_at')->nullable()->comment('Timestamp when a web order or resumed hold received its final business number.');
            $table->timestamp('completed_at')->nullable()->comment('Timestamp when fulfillment or POS checkout completed.');
            $table->timestamp('cancelled_at')->nullable()->comment('Timestamp when an eligible order entered the cancelled state.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the order aggregate was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the order aggregate was last updated.');

            $table->index(['channel', 'status', 'created_at'], 'orders_channel_status_index');
            $table->index(['payment_status', 'created_at'], 'orders_payment_status_index');
            $table->index(['customer_id', 'created_at'], 'orders_customer_index');
            $table->index(['user_id', 'created_at'], 'orders_user_index');
            $table->index(['till_session_id', 'created_at'], 'orders_till_index');
            $table->index('placed_at', 'orders_placed_at_index');
        });
    }

    /**
     * Remove unified order headers.
     */
    public function down(): void
    {
        Schema::dropIfExists('orders');
    }
};
