<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the append-only inventory movement ledger.
 */
return new class extends Migration
{
    /**
     * Create stock movements with before/after reconciliation snapshots.
     */
    public function up(): void
    {
        Schema::create('stock_movements', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for ledger ordering.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid.');
            $table->foreignId('product_id')->comment('Product whose stock projection changed.')->constrained('products')->cascadeOnDelete();
            $table->string('type', 30)->comment('Ledger event backed by Inventory Enums StockMovementType.');
            $table->bigInteger('quantity_delta')->comment('Signed integer unit change; positive adds stock and negative removes stock.');
            $table->bigInteger('balance_before')->comment('Locked stock projection immediately before this movement.');
            $table->bigInteger('balance_after')->comment('Stock projection immediately after this movement.');
            $table->string('reference_type')->nullable()->comment('Optional polymorphic class name for the order or future source aggregate.');
            $table->unsignedBigInteger('reference_id')->nullable()->comment('Optional integer primary key of the polymorphic source aggregate.');
            $table->string('note', 255)->nullable()->comment('Short human-readable reason safe for ledger display.');
            $table->foreignId('created_by')->nullable()->comment('User responsible for the movement when an authenticated actor exists.')->constrained('users')->nullOnDelete();
            $table->timestamp('created_at')->comment('Immutable timestamp when the stock movement was posted.');

            $table->index(['product_id', 'created_at'], 'stock_movements_product_time_index');
            $table->index(['reference_type', 'reference_id'], 'stock_movements_reference_index');
            $table->index(['type', 'created_at'], 'stock_movements_type_time_index');
        });
    }

    /**
     * Remove the stock movement ledger.
     */
    public function down(): void
    {
        Schema::dropIfExists('stock_movements');
    }
};
