<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the hierarchical catalog category registry.
 */
return new class extends Migration
{
    /**
     * Create product categories with ULID administration identity and slug URLs.
     */
    public function up(): void
    {
        Schema::create('product_categories', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for relationship storage.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid.');
            $table->foreignId('parent_id')->nullable()->comment('Optional parent category for hierarchical navigation.')->constrained('product_categories')->nullOnDelete();
            $table->string('name', 120)->comment('Human-readable category name displayed in administration and storefront navigation.');
            $table->string('slug', 160)->unique()->comment('Unique readable category key used by public storefront routes.');
            $table->text('description')->nullable()->comment('Optional category introduction displayed on category landing pages.');
            $table->string('meta_title', 160)->nullable()->comment('Optional browser and search metadata title for the category page.');
            $table->string('meta_description', 320)->nullable()->comment('Optional browser and search metadata description for the category page.');
            $table->unsignedInteger('sort_order')->default(0)->comment('Ascending manual order within the same category level.');
            $table->boolean('is_active')->default(true)->comment('Whether the category is available to storefront catalog queries.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the category record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the category record was last updated.');

            $table->index(['parent_id', 'is_active', 'sort_order'], 'categories_navigation_index');
        });
    }

    /**
     * Remove the category registry.
     */
    public function down(): void
    {
        Schema::dropIfExists('product_categories');
    }
};
