<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates reusable customer records shared by storefront and POS.
 */
return new class extends Migration
{
    /**
     * Create lightweight customer identity and default-address records.
     */
    public function up(): void
    {
        Schema::create('customers', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for customer relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid.');
            $table->foreignId('user_id')->nullable()->unique()->comment('Optional authenticated Aureon account linked to this customer.')->constrained('users')->nullOnDelete();
            $table->foreignId('created_by')->nullable()->comment('Staff user who created the reusable customer record, when applicable.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('Staff user who most recently updated the customer record.')->constrained('users')->nullOnDelete();
            $table->string('first_name', 100)->comment('Customer given or first name.');
            $table->string('last_name', 100)->comment('Customer family or last name.');
            $table->string('company', 160)->nullable()->comment('Optional customer organization or business name.');
            $table->string('tax_identifier', 80)->nullable()->comment('Optional customer tax or business registration identifier for invoices.');
            $table->string('email', 255)->nullable()->comment('Customer contact email; intentionally not globally unique.');
            $table->string('phone', 40)->nullable()->comment('Customer contact telephone number; intentionally not globally unique.');
            $table->string('address_line_1', 180)->nullable()->comment('Default street, building, or delivery address line.');
            $table->string('address_line_2', 180)->nullable()->comment('Optional continuation of the default delivery address.');
            $table->string('city', 100)->nullable()->comment('Default customer city or locality.');
            $table->string('region', 100)->nullable()->comment('Default county, state, province, or region.');
            $table->string('postal_code', 30)->nullable()->comment('Optional default postal or ZIP code.');
            $table->char('country_code', 2)->default('KE')->comment('Default ISO 3166-1 alpha-2 country code.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the customer record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the customer record was last updated.');
            $table->timestamp('deleted_at')->nullable()->comment('Soft-deletion timestamp preserving historical order snapshots.');

            $table->index('email', 'customers_email_index');
            $table->index('phone', 'customers_phone_index');
            $table->index(['last_name', 'first_name'], 'customers_name_index');
        });
    }

    /**
     * Remove reusable customer records.
     */
    public function down(): void
    {
        Schema::dropIfExists('customers');
    }
};
