<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates named POS register endpoints.
 */
return new class extends Migration
{
    /**
     * Create registers that may own one open till session at a time.
     */
    public function up(): void
    {
        Schema::create('registers', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for POS relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid.');
            $table->string('name', 100)->comment('Human-readable register name displayed to cashiers.');
            $table->string('code', 40)->unique()->comment('Stable unique operational code used in reporting and configuration.');
            $table->string('location_label', 160)->nullable()->comment('Optional physical placement label without introducing multi-location inventory.');
            $table->text('description')->nullable()->comment('Optional internal description or operating note for the register.');
            $table->boolean('is_active')->default(true)->comment('Whether a new till session may be opened on the register.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the register was configured.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the register configuration was last updated.');
        });
    }

    /**
     * Remove POS register configuration.
     */
    public function down(): void
    {
        Schema::dropIfExists('registers');
    }
};
