<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates manual storefront payment and POS tender records.
 */
return new class extends Migration
{
    /**
     * Create payment records with applied, tendered, and change snapshots.
     */
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for payment relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid.');
            $table->foreignId('order_id')->comment('Order settled or intended to be settled by this payment.')->constrained('orders')->cascadeOnDelete();
            $table->foreignId('till_session_id')->nullable()->comment('POS till session that received the tender.')->constrained('till_sessions')->nullOnDelete();
            $table->foreignId('recorded_by')->nullable()->comment('Staff user who recorded or confirmed the payment.')->constrained('users')->nullOnDelete();
            $table->string('method', 30)->comment('Tender or preference backed by Orders Enums PaymentMethod.');
            $table->string('status', 20)->default('pending')->comment('Payment lifecycle backed by Orders Enums PaymentStatus.');
            $table->unsignedBigInteger('amount_minor')->comment('Amount applied to the order balance in order currency minor units.');
            $table->unsignedBigInteger('tendered_minor')->nullable()->comment('Physical or submitted tender amount before cash change in currency minor units.');
            $table->unsignedBigInteger('change_minor')->default(0)->comment('Cash returned to the customer in currency minor units.');
            $table->string('reference', 120)->nullable()->comment('Sanitized M-Pesa, card, bank, or manual confirmation reference.');
            $table->json('metadata')->nullable()->comment('Sanitized non-sensitive provider or reconciliation context.');
            $table->timestamp('paid_at')->nullable()->comment('Timestamp when the payment became completed and applicable to the order.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the payment record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the payment lifecycle was last updated.');

            $table->index(['order_id', 'status'], 'payments_order_status_index');
            $table->index(['till_session_id', 'status'], 'payments_till_status_index');
            $table->index('reference', 'payments_reference_index');
            $table->index('paid_at', 'payments_paid_at_index');
        });
    }

    /**
     * Remove payment and tender records.
     */
    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
