<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates cashier till sessions and closing reconciliation snapshots.
 */
return new class extends Migration
{
    /**
     * Create till sessions linked to a register and responsible users.
     */
    public function up(): void
    {
        Schema::create('till_sessions', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for POS transaction relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid.');
            $table->foreignId('register_id')->comment('POS register operated during this till session.')->constrained('registers')->restrictOnDelete();
            $table->foreignId('opened_by')->comment('User who opened and initially owns the till session.')->constrained('users')->restrictOnDelete();
            $table->foreignId('closed_by')->nullable()->comment('User who performed the closing reconciliation.')->constrained('users')->nullOnDelete();
            $table->string('status', 20)->default('open')->comment('Lifecycle state backed by PointOfSale Enums TillSessionStatus.');
            $table->unsignedBigInteger('opening_float_minor')->default(0)->comment('Cash placed in the till at opening in configured currency minor units.');
            $table->unsignedBigInteger('expected_cash_minor')->default(0)->comment('Opening float plus completed cash payments in configured currency minor units.');
            $table->unsignedBigInteger('counted_cash_minor')->nullable()->comment('Physical cash counted during close in configured currency minor units.');
            $table->bigInteger('variance_minor')->nullable()->comment('Signed counted-minus-expected cash difference in configured currency minor units.');
            $table->text('opening_note')->nullable()->comment('Optional operational note recorded when the till is opened.');
            $table->text('closing_note')->nullable()->comment('Optional explanation recorded during till reconciliation.');
            $table->timestamp('opened_at')->comment('Timestamp when the register session became available for sales.');
            $table->timestamp('closed_at')->nullable()->comment('Timestamp when the register session was reconciled and closed.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the till session record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the till session record was last updated.');

            $table->index(['register_id', 'status'], 'till_register_status_index');
            $table->index(['opened_by', 'status'], 'till_cashier_status_index');
            $table->index('opened_at', 'till_opened_at_index');
        });
    }

    /**
     * Remove till session and reconciliation records.
     */
    public function down(): void
    {
        Schema::dropIfExists('till_sessions');
    }
};
