<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the shared simple-product catalog used by storefront and POS.
 */
return new class extends Migration
{
    /**
     * Create products with pricing, publication, physical, tax, and stock policy fields.
     */
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for relationship and media storage.');
            $table->ulid('ulid')->unique()->comment('Immutable external route identifier generated by HasUlid.');
            $table->foreignId('category_id')->nullable()->comment('Optional primary product category.')->constrained('product_categories')->nullOnDelete();
            $table->foreignId('created_by')->nullable()->comment('Administrator who originally created the product.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('Administrator who most recently updated the product.')->constrained('users')->nullOnDelete();
            $table->string('name', 180)->comment('Product name displayed in catalog, POS, receipts, and order snapshots.');
            $table->string('slug', 200)->unique()->comment('Unique readable product key used by public storefront routes.');
            $table->string('sku', 80)->unique()->comment('Unique internal stock-keeping code used by search and POS entry.');
            $table->string('barcode', 80)->nullable()->unique()->comment('Optional unique scanner barcode supplied by a keyboard-wedge device.');
            $table->string('status', 30)->default('draft')->comment('Publication lifecycle backed by Catalog Enums ProductStatus.');
            $table->text('short_description')->nullable()->comment('Concise storefront and POS product summary.');
            $table->longText('description')->nullable()->comment('Full product description rendered on the product detail page.');
            $table->json('specifications')->nullable()->comment('Optional structured product specification groups and values.');
            $table->string('unit_label', 30)->default('item')->comment('Singular unit label displayed beside integer quantities.');
            $table->unsignedInteger('minimum_order_quantity')->default(1)->comment('Smallest quantity accepted by storefront and POS carts.');
            $table->unsignedInteger('maximum_order_quantity')->nullable()->comment('Optional per-order quantity cap; null means no product-specific cap.');
            $table->unsignedBigInteger('price_minor')->comment('Regular unit selling price in configured currency minor units.');
            $table->unsignedBigInteger('sale_price_minor')->nullable()->comment('Optional promotional unit price in configured currency minor units.');
            $table->timestamp('sale_starts_at')->nullable()->comment('Optional timestamp when promotional pricing becomes active.');
            $table->timestamp('sale_ends_at')->nullable()->comment('Optional timestamp when promotional pricing stops being active.');
            $table->unsignedBigInteger('cost_price_minor')->nullable()->comment('Internal unit acquisition cost in configured currency minor units.');
            $table->unsignedSmallInteger('tax_rate_bps')->default(0)->comment('Product tax rate in basis points where 1600 represents 16 percent.');
            $table->boolean('is_tax_inclusive')->default(true)->comment('Whether the stored selling prices already include product tax.');
            $table->boolean('track_stock')->default(true)->comment('Whether checkout must enforce the product stock projection.');
            $table->unsignedBigInteger('weight_grams')->nullable()->comment('Optional product weight in grams for delivery and specification display.');
            $table->unsignedInteger('length_mm')->nullable()->comment('Optional packaged product length in millimetres.');
            $table->unsignedInteger('width_mm')->nullable()->comment('Optional packaged product width in millimetres.');
            $table->unsignedInteger('height_mm')->nullable()->comment('Optional packaged product height in millimetres.');
            $table->boolean('is_featured')->default(false)->comment('Whether the storefront may include the product in featured selections.');
            $table->string('meta_title', 160)->nullable()->comment('Optional browser and search metadata title for the product page.');
            $table->string('meta_description', 320)->nullable()->comment('Optional browser and search metadata description for the product page.');
            $table->timestamp('published_at')->nullable()->comment('Timestamp from which the published product may appear publicly.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the product record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the product record was last updated.');
            $table->timestamp('deleted_at')->nullable()->comment('Soft-deletion timestamp preserving historical order relationships.');

            $table->index(['status', 'published_at'], 'products_publication_index');
            $table->index(['category_id', 'status'], 'products_category_status_index');
            $table->index(['is_featured', 'status'], 'products_featured_status_index');
            $table->index('name', 'products_name_index');
        });
    }

    /**
     * Remove the product catalog.
     */
    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};
