@extends($reportContext->orientation->layout())
@section('content')
    <table class="report-meta-table">
        <tr><td><strong>Booking</strong><br>{{ $booking->booking_number }}</td><td><strong>Status</strong><br>{{ $booking->status->label() }}</td><td><strong>Payment</strong><br>{{ $booking->payment_status->label() }}</td></tr>
        <tr><td><strong>Customer</strong><br>{{ $booking->customer_name_snapshot }}</td><td><strong>Tour</strong><br>{{ $booking->tour_name_snapshot }}</td><td><strong>Participants</strong><br>{{ $booking->adult_count + $booking->child_count + $booking->infant_count }}</td></tr>
        <tr><td colspan="2"><strong>Travel window</strong><br>{{ $booking->departure_starts_at_snapshot->timezone($booking->departure_timezone_snapshot)->format('d M Y, H:i') }} - {{ $booking->departure_ends_at_snapshot->timezone($booking->departure_timezone_snapshot)->format('d M Y, H:i') }}</td><td><strong>Timezone</strong><br>{{ $booking->departure_timezone_snapshot }}</td></tr>
    </table>
    <h3>Travelers</h3>
    <table class="report-table"><thead><tr><th>Name</th><th>Type</th><th>Nationality</th><th class="amount">Allocated fare</th></tr></thead><tbody>@foreach($booking->participants as $participant)<tr><td>{{ trim($participant->first_name.' '.$participant->middle_name.' '.$participant->last_name) }}</td><td>{{ $participant->participant_type->label() }}</td><td>{{ $participant->nationality_code ?: 'Not supplied' }}</td><td class="amount">{{ \App\Modules\TravelTours\Support\MoneyFormatter::format($participant->allocated_price_minor, $booking->currency, $booking->currency_exponent) }}</td></tr>@endforeach</tbody></table>
    <h3>Price summary</h3>
    <table class="report-table"><thead><tr><th>Description</th><th>Quantity</th><th class="amount">Amount</th></tr></thead><tbody>@foreach($booking->priceLines as $line)<tr><td>{{ $line->description }}</td><td>{{ $line->quantity }}</td><td class="amount">{{ \App\Modules\TravelTours\Support\MoneyFormatter::format($line->total_minor, $booking->currency, $booking->currency_exponent) }}</td></tr>@endforeach</tbody></table>
    <table class="report-totals"><tr><th>Subtotal</th><td>{{ \App\Modules\TravelTours\Support\MoneyFormatter::format($booking->subtotal_minor, $booking->currency, $booking->currency_exponent) }}</td></tr><tr><th>Discount</th><td>{{ \App\Modules\TravelTours\Support\MoneyFormatter::format($booking->discount_total_minor, $booking->currency, $booking->currency_exponent) }}</td></tr><tr><th>Tax</th><td>{{ \App\Modules\TravelTours\Support\MoneyFormatter::format($booking->tax_total_minor, $booking->currency, $booking->currency_exponent) }}</td></tr><tr><th>Total</th><td>{{ \App\Modules\TravelTours\Support\MoneyFormatter::format($booking->total_minor, $booking->currency, $booking->currency_exponent) }}</td></tr><tr><th>Paid</th><td>{{ \App\Modules\TravelTours\Support\MoneyFormatter::format($booking->paid_minor, $booking->currency, $booking->currency_exponent) }}</td></tr></table>
    @if($booking->special_requests)<h3>Special requests</h3><p>{{ $booking->special_requests }}</p>@endif
    <p class="report-note">This summary is generated from immutable booking and pricing snapshots. Travel-document and medical details are intentionally excluded.</p>
@endsection
