<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates sellable accommodation descriptions within each property. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_unit_types', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for unit-type relationships and locking.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('property_id')->comment('Property that owns and sells this accommodation type.')->constrained('property_booking_properties')->cascadeOnDelete();
            $table->foreignId('created_by')->nullable()->comment('User who created the unit type.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('User who most recently changed the unit type.')->constrained('users')->nullOnDelete();
            $table->string('code', 40)->comment('Stable operational unit-type code unique within its property.');
            $table->string('slug', 180)->comment('URL-safe unit-type identifier unique within its property.');
            $table->string('name', 180)->comment('Public sellable unit-type name.');
            $table->string('status', 20)->default('draft')->comment('Publication lifecycle backed by Catalog Enums UnitTypeStatus.');
            $table->string('short_description', 320)->nullable()->comment('Compact public summary used on search cards.');
            $table->longText('description')->nullable()->comment('Full public description of layout, furnishing, and experience.');
            $table->decimal('size_square_metres', 8, 2)->nullable()->comment('Approximate floor area in square metres.');
            $table->unsignedSmallInteger('bedroom_count')->default(0)->comment('Number of bedrooms represented by one concrete unit.');
            $table->unsignedSmallInteger('bathroom_count')->default(1)->comment('Number of bathrooms represented by one concrete unit.');
            $table->unsignedSmallInteger('living_room_count')->default(0)->comment('Number of living rooms represented by one concrete unit.');
            $table->unsignedSmallInteger('bed_count')->default(1)->comment('Total physical beds represented by one concrete unit.');
            $table->json('bed_configuration')->nullable()->comment('Validated structured bed labels and quantities used for display.');
            $table->unsignedSmallInteger('maximum_guests')->default(1)->comment('Maximum total chargeable guests excluding permitted infants-on-top.');
            $table->unsignedSmallInteger('maximum_adults')->default(1)->comment('Maximum adult occupants.');
            $table->unsignedSmallInteger('maximum_children')->default(0)->comment('Maximum child occupants.');
            $table->unsignedSmallInteger('maximum_infants')->default(0)->comment('Maximum infant occupants.');
            $table->boolean('allows_infants_on_top')->default(true)->comment('Whether infants may be added without consuming maximum_guests capacity.');
            $table->boolean('is_entire_unit')->default(true)->comment('Whether the guest books the entire concrete unit rather than shared space.');
            $table->boolean('smoking_allowed')->default(false)->comment('Whether smoking is permitted for this unit type.');
            $table->boolean('is_featured')->default(false)->comment('Whether the unit type receives featured storefront placement.');
            $table->string('meta_title', 160)->nullable()->comment('Optional search and social title override.');
            $table->string('meta_description', 320)->nullable()->comment('Optional search and social description override.');
            $table->timestamp('published_at')->nullable()->comment('UTC timestamp when the unit type became publicly eligible.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the unit type was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the unit type was last changed.');
            $table->softDeletes()->comment('Timestamp when the unit type was archived from ordinary queries.');

            $table->unique(['property_id', 'code'], 'pb_unit_types_property_code_unique');
            $table->unique(['property_id', 'slug'], 'pb_unit_types_property_slug_unique');
            $table->index(['property_id', 'status', 'published_at'], 'pb_unit_types_public_index');
            $table->index(['property_id', 'maximum_guests', 'status'], 'pb_unit_types_occupancy_index');
            $table->index(['property_id', 'is_featured', 'status'], 'pb_unit_types_featured_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_unit_types');
    }
};
