<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates property-scoped reception endpoints and receipt settings. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_registers', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for reception-shift relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('property_id')->comment('Property operated by this reception endpoint.')->constrained('property_booking_properties')->cascadeOnDelete();
            $table->foreignId('created_by')->nullable()->comment('User who configured the register.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('User who most recently changed the register.')->constrained('users')->nullOnDelete();
            $table->string('code', 40)->comment('Stable register code unique within its property.');
            $table->string('name', 120)->comment('Human-readable reception endpoint name.');
            $table->string('location_label', 160)->nullable()->comment('Optional desk, lobby, wing, or building location label.');
            $table->text('description')->nullable()->comment('Optional internal description or operating note.');
            $table->string('receipt_print_driver', 60)->default('browser')->comment('Configured module receipt-printer driver key.');
            $table->string('receipt_print_mode', 20)->default('manual')->comment('Print behavior backed by PointOfBooking Enums ReceiptPrintMode.');
            $table->unsignedSmallInteger('receipt_paper_width')->default(80)->comment('Thermal-roll width in millimetres backed by ReceiptPaperWidth.');
            $table->string('receipt_printer_name', 160)->nullable()->comment('Optional workstation printer name passed only to a supporting adapter.');
            $table->boolean('is_active')->default(true)->comment('Whether a new reception shift may be opened on this register.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the register was configured.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the register was last changed.');
            $table->softDeletes()->comment('Timestamp when the register was retired from ordinary queries.');

            $table->unique(['property_id', 'code'], 'pb_registers_property_code_unique');
            $table->index(['property_id', 'is_active'], 'pb_registers_property_active_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_registers');
    }
};
