<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates reusable property and unit-type amenities. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_amenities', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for amenity relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->string('name', 120)->unique()->comment('Unique human-readable amenity name.');
            $table->string('slug', 150)->unique()->comment('Unique URL-safe amenity identifier.');
            $table->string('scope', 20)->default('both')->comment('Allowed assignment level backed by Catalog Enums AmenityScope.');
            $table->text('description')->nullable()->comment('Optional public explanation of the facility or feature.');
            $table->string('icon_key', 80)->nullable()->comment('Validated icon-library key; raw markup is never stored.');
            $table->unsignedInteger('sort_order')->default(0)->comment('Ascending display priority.');
            $table->boolean('is_active')->default(true)->comment('Whether the amenity may be assigned and displayed.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the amenity was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the amenity was last changed.');

            $table->index(['scope', 'is_active', 'sort_order'], 'pb_amenities_scope_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_amenities');
    }
};
