<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates compensating non-accommodation charges against bookings. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_charges', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for charge lifecycle operations.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('booking_id')->comment('Booking aggregate receiving this charge.')->constrained('property_bookings')->cascadeOnDelete();
            $table->foreignId('booking_stay_id')->nullable()->comment('Optional stay line specifically associated with the charge.')->constrained('property_booking_stays')->nullOnDelete();
            $table->foreignId('reception_shift_id')->nullable()->comment('Reception shift responsible for a POB-posted charge.')->constrained('property_booking_shifts')->nullOnDelete();
            $table->string('type', 20)->comment('Charge classification backed by Bookings Enums BookingChargeType.');
            $table->string('status', 20)->default('posted')->comment('Compensating lifecycle backed by Bookings Enums BookingChargeStatus.');
            $table->string('description', 180)->comment('Guest-safe description rendered on booking documents.');
            $table->unsignedInteger('quantity')->default(1)->comment('Whole quantity multiplied by unit amount.');
            $table->unsignedBigInteger('unit_amount_minor')->comment('Price for one quantity unit in currency minor units.');
            $table->unsignedBigInteger('subtotal_minor')->comment('Quantity multiplied by unit amount before tax treatment.');
            $table->unsignedSmallInteger('tax_rate_bps')->default(0)->comment('Charge tax rate in basis points.');
            $table->unsignedBigInteger('tax_minor')->default(0)->comment('Tax attributable to this charge in currency minor units.');
            $table->unsignedBigInteger('total_minor')->comment('Final charge amount in currency minor units.');
            $table->boolean('is_tax_inclusive')->default(true)->comment('Whether unit_amount_minor already includes tax.');
            $table->foreignId('posted_by')->comment('Authorized user who posted the charge.')->constrained('users')->restrictOnDelete();
            $table->timestamp('posted_at')->comment('UTC timestamp when the charge entered booking totals.');
            $table->foreignId('voided_by')->nullable()->comment('Authorized user who voided the charge.')->constrained('users')->nullOnDelete();
            $table->timestamp('voided_at')->nullable()->comment('UTC timestamp when the charge stopped contributing to totals.');
            $table->string('void_reason', 255)->nullable()->comment('Required staff-readable reason for a void.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the charge was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the charge lifecycle last changed.');

            $table->index(['booking_id', 'status'], 'pb_charges_booking_status_index');
            $table->index(['reception_shift_id', 'status'], 'pb_charges_shift_status_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_charges');
    }
};
