<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates reusable guest contact and protected identity records. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_guests', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for booking and occupant relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('user_id')->nullable()->unique()->comment('Optional Aureon account linked one-to-one with this guest.')->constrained('users')->nullOnDelete();
            $table->foreignId('created_by')->nullable()->comment('Staff user who created the guest record, null for self-service creation.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('User who most recently changed the guest record.')->constrained('users')->nullOnDelete();
            $table->string('title', 30)->nullable()->comment('Optional courtesy title.');
            $table->string('first_name', 100)->comment('Guest legal or preferred first name.');
            $table->string('middle_name', 100)->nullable()->comment('Optional guest middle name.');
            $table->string('last_name', 100)->comment('Guest legal or preferred last name.');
            $table->string('email', 255)->nullable()->comment('Normalized guest email address.');
            $table->string('phone', 40)->nullable()->comment('Normalized primary guest telephone number.');
            $table->string('alternate_phone', 40)->nullable()->comment('Optional normalized alternate telephone number.');
            $table->date('date_of_birth')->nullable()->comment('Guest date of birth where law or policy requires it.');
            $table->char('nationality_country_code', 2)->nullable()->comment('ISO 3166-1 alpha-2 nationality code.');
            $table->string('identity_type', 40)->nullable()->comment('Validated identity document class such as national_id or passport.');
            $table->text('identity_number_ciphertext')->nullable()->comment('Application-encrypted identity number; never logged or rendered on receipts.');
            $table->char('identity_number_hash', 64)->nullable()->comment('Keyed HMAC of the normalized identity number for exact-match lookup.');
            $table->char('identity_country_code', 2)->nullable()->comment('ISO 3166-1 alpha-2 issuing country code.');
            $table->string('address_line_1', 180)->nullable()->comment('Primary guest address line.');
            $table->string('address_line_2', 180)->nullable()->comment('Optional continuation of the guest address.');
            $table->string('city', 100)->nullable()->comment('Guest address city or locality.');
            $table->string('region', 100)->nullable()->comment('Guest address county, state, province, or region.');
            $table->string('postal_code', 30)->nullable()->comment('Guest postal or ZIP code.');
            $table->char('country_code', 2)->nullable()->comment('ISO 3166-1 alpha-2 guest residence country code.');
            $table->string('emergency_contact_name', 160)->nullable()->comment('Optional emergency contact display name.');
            $table->string('emergency_contact_phone', 40)->nullable()->comment('Optional normalized emergency contact telephone number.');
            $table->text('note')->nullable()->comment('Staff-only guest service note without payment or document secrets.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the guest record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the guest record was last changed.');
            $table->softDeletes()->comment('Timestamp when the guest was archived from ordinary queries.');

            $table->unique(['identity_type', 'identity_number_hash'], 'pb_guests_identity_unique');
            $table->index('email', 'pb_guests_email_index');
            $table->index('phone', 'pb_guests_phone_index');
            $table->index(['last_name', 'first_name'], 'pb_guests_name_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_guests');
    }
};
