<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates concrete assignable rooms, apartments, houses, and spaces. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_units', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key used for deterministic allocation locks.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('property_id')->comment('Property that physically owns the concrete unit.')->constrained('property_booking_properties')->cascadeOnDelete();
            $table->foreignId('unit_type_id')->comment('Sellable accommodation description represented by this unit.')->constrained('property_booking_unit_types')->cascadeOnDelete();
            $table->foreignId('created_by')->nullable()->comment('User who created the concrete unit.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('User who most recently changed the concrete unit.')->constrained('users')->nullOnDelete();
            $table->string('code', 60)->comment('Stable room, house, apartment, or inventory code unique within its property.');
            $table->string('display_name', 140)->nullable()->comment('Optional guest-facing unit name; the operational code remains canonical.');
            $table->string('floor_label', 80)->nullable()->comment('Optional floor, wing, block, or level label.');
            $table->string('location_note', 180)->nullable()->comment('Optional concise physical finding instruction for staff.');
            $table->string('operational_status', 30)->default('ready')->comment('Readiness state backed by Catalog Enums UnitOperationalStatus.');
            $table->boolean('is_active')->default(true)->comment('Whether this unit may participate in future allocation.');
            $table->text('internal_note')->nullable()->comment('Staff-only operational note never rendered publicly.');
            $table->timestamp('last_ready_at')->nullable()->comment('UTC timestamp when the unit most recently became ready.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the concrete unit was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the concrete unit was last changed.');
            $table->softDeletes()->comment('Timestamp when the unit was archived from ordinary queries.');

            $table->unique(['property_id', 'code'], 'pb_units_property_code_unique');
            $table->index(['unit_type_id', 'is_active', 'operational_status'], 'pb_units_allocation_index');
            $table->index(['property_id', 'operational_status'], 'pb_units_property_status_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_units');
    }
};
