<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates accommodation establishments and their default operating policy. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_properties', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for property relationships and locking.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('category_id')->nullable()->comment('Optional establishment category.')->constrained('property_booking_categories')->nullOnDelete();
            $table->foreignId('created_by')->nullable()->comment('User who created the property record.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('User who most recently changed the property record.')->constrained('users')->nullOnDelete();
            $table->string('code', 40)->unique()->comment('Stable globally unique operational property code.');
            $table->string('slug', 180)->unique()->comment('Globally unique URL-safe public property identifier.');
            $table->string('name', 180)->comment('Public establishment name.');
            $table->string('status', 20)->default('draft')->comment('Publication lifecycle backed by Catalog Enums PropertyStatus.');
            $table->string('short_description', 320)->nullable()->comment('Compact public summary used on property cards.');
            $table->longText('description')->nullable()->comment('Full public description of the establishment and experience.');
            $table->longText('house_rules')->nullable()->comment('Public guest conduct, access, and occupancy rules.');
            $table->text('cancellation_summary')->nullable()->comment('Public summary of the property-level cancellation policy.');
            $table->string('email', 255)->nullable()->comment('Public property contact email address.');
            $table->string('phone', 40)->nullable()->comment('Public property contact telephone number.');
            $table->string('whatsapp_phone', 40)->nullable()->comment('Optional normalized WhatsApp contact number.');
            $table->string('website_url', 2048)->nullable()->comment('Optional canonical external website URL.');
            $table->string('address_line_1', 180)->nullable()->comment('Primary physical street, building, or locality address.');
            $table->string('address_line_2', 180)->nullable()->comment('Optional continuation of the physical address.');
            $table->string('city', 100)->nullable()->comment('Property city or locality.');
            $table->string('region', 100)->nullable()->comment('Property county, state, province, or region.');
            $table->string('postal_code', 30)->nullable()->comment('Property postal or ZIP code.');
            $table->char('country_code', 2)->default('KE')->comment('ISO 3166-1 alpha-2 property country code.');
            $table->decimal('latitude', 10, 7)->nullable()->comment('Signed WGS84 latitude validated to the range -90 through 90.');
            $table->decimal('longitude', 10, 7)->nullable()->comment('Signed WGS84 longitude validated to the range -180 through 180.');
            $table->string('timezone', 64)->default('Africa/Nairobi')->comment('IANA timezone used for local booking calendars and policy windows.');
            $table->char('currency', 3)->default('KES')->comment('ISO 4217 currency used by all version-one rates for this property.');
            $table->time('check_in_from')->nullable()->comment('Earliest normal property-local check-in time.');
            $table->time('check_in_until')->nullable()->comment('Latest normal property-local check-in time.');
            $table->time('check_out_from')->nullable()->comment('Earliest normal property-local check-out time.');
            $table->time('check_out_until')->nullable()->comment('Latest normal property-local check-out time.');
            $table->unsignedInteger('minimum_notice_minutes')->default(0)->comment('Minimum lead time required before a stay begins.');
            $table->unsignedInteger('maximum_advance_days')->nullable()->comment('Maximum number of days before arrival that a booking may be placed.');
            $table->unsignedInteger('turnover_minutes')->default(60)->comment('Cleaning buffer applied after each departure in overlap checks.');
            $table->boolean('is_featured')->default(false)->comment('Whether the property receives featured storefront placement.');
            $table->string('meta_title', 160)->nullable()->comment('Optional search and social title override.');
            $table->string('meta_description', 320)->nullable()->comment('Optional search and social description override.');
            $table->timestamp('published_at')->nullable()->comment('UTC timestamp when the property became publicly eligible.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the property record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the property record was last changed.');
            $table->softDeletes()->comment('Timestamp when the property was archived from ordinary queries.');

            $table->index(['status', 'published_at'], 'pb_properties_publication_index');
            $table->index(['category_id', 'status'], 'pb_properties_category_index');
            $table->index(['is_featured', 'status'], 'pb_properties_featured_index');
            $table->index(['country_code', 'region', 'city'], 'pb_properties_location_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_properties');
    }
};
