<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates bounded local-date rate and restriction overrides. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_rate_overrides', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for rate-override relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('rate_plan_id')->comment('Rate plan receiving this bounded override.')->constrained('property_booking_rate_plans')->cascadeOnDelete();
            $table->foreignId('created_by')->nullable()->comment('User who created the override.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('User who most recently changed the override.')->constrained('users')->nullOnDelete();
            $table->date('starts_on')->comment('Inclusive first property-local calendar date affected by the override.');
            $table->date('ends_on')->comment('Exclusive property-local calendar date ending the override.');
            $table->unsignedBigInteger('rate_minor')->nullable()->comment('Optional replacement base rate in currency minor units.');
            $table->boolean('is_closed')->default(false)->comment('Whether the rate is unavailable throughout this date interval.');
            $table->boolean('closed_on_arrival')->default(false)->comment('Whether a stay may not begin within this date interval.');
            $table->boolean('closed_on_departure')->default(false)->comment('Whether a stay may not end within this date interval.');
            $table->unsignedSmallInteger('minimum_units')->nullable()->comment('Optional replacement minimum stay duration in billing units.');
            $table->unsignedSmallInteger('maximum_units')->nullable()->comment('Optional replacement maximum stay duration in billing units.');
            $table->string('reason', 180)->nullable()->comment('Concise staff-readable reason for the override.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the override was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the override was last changed.');

            $table->index(['rate_plan_id', 'starts_on', 'ends_on'], 'pb_rate_overrides_interval_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_rate_overrides');
    }
};
