<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates hierarchical categories for accommodation establishments. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_categories', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for category relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('parent_id')->nullable()->comment('Optional parent category used for a shallow establishment taxonomy.')->constrained('property_booking_categories')->nullOnDelete();
            $table->string('name', 120)->comment('Human-readable category name such as Hotel, Apartment, or House.');
            $table->string('slug', 150)->unique()->comment('Globally unique URL-safe category identifier.');
            $table->text('description')->nullable()->comment('Optional public explanation of the establishment category.');
            $table->unsignedInteger('sort_order')->default(0)->comment('Ascending display priority within the category navigation.');
            $table->boolean('is_active')->default(true)->comment('Whether the category may be selected and displayed publicly.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the category was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the category was last changed.');

            $table->index(['parent_id', 'is_active', 'sort_order'], 'pb_categories_navigation_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_categories');
    }
};
