<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates bookable prices, occupancy rules, and cancellation policy. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_rate_plans', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for pricing relationships and locks.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('property_id')->comment('Property whose currency and policy context govern this rate.')->constrained('property_booking_properties')->cascadeOnDelete();
            $table->foreignId('unit_type_id')->comment('Sellable accommodation type priced by this plan.')->constrained('property_booking_unit_types')->cascadeOnDelete();
            $table->foreignId('created_by')->nullable()->comment('User who created the rate plan.')->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->comment('User who most recently changed the rate plan.')->constrained('users')->nullOnDelete();
            $table->string('code', 40)->comment('Stable rate code unique within the unit type.');
            $table->string('name', 160)->comment('Guest-facing rate plan name.');
            $table->text('description')->nullable()->comment('Optional public inclusions and positioning for the rate.');
            $table->string('status', 20)->default('draft')->comment('Administrative lifecycle backed by Pricing Enums RatePlanStatus.');
            $table->string('pricing_unit', 20)->comment('Short-stay billing basis backed by Pricing Enums StayPricingUnit.');
            $table->char('currency', 3)->comment('ISO 4217 currency matching the owning property in version one.');
            $table->unsignedBigInteger('base_rate_minor')->comment('Base price for one billable unit in currency minor units.');
            $table->unsignedSmallInteger('included_adults')->default(1)->comment('Adult occupants included in the base rate.');
            $table->unsignedSmallInteger('included_children')->default(0)->comment('Child occupants included in the base rate.');
            $table->unsignedBigInteger('extra_adult_minor')->default(0)->comment('Surcharge per extra adult per billable unit in currency minor units.');
            $table->unsignedBigInteger('extra_child_minor')->default(0)->comment('Surcharge per extra child per billable unit in currency minor units.');
            $table->unsignedSmallInteger('minimum_units')->default(1)->comment('Minimum whole billing units permitted for the rate.');
            $table->unsignedSmallInteger('maximum_units')->nullable()->comment('Optional maximum whole billing units permitted for the rate.');
            $table->unsignedInteger('minimum_advance_minutes')->default(0)->comment('Minimum lead time required before the stay begins.');
            $table->unsignedInteger('maximum_advance_days')->nullable()->comment('Optional maximum advance-booking window in local calendar days.');
            $table->unsignedSmallInteger('tax_rate_bps')->default(0)->comment('Tax rate in basis points where 100 basis points equals one percent.');
            $table->boolean('is_tax_inclusive')->default(true)->comment('Whether base and surcharge amounts already include tax.');
            $table->string('deposit_type', 20)->default('none')->comment('Deposit strategy backed by Pricing Enums DepositType.');
            $table->unsignedBigInteger('deposit_amount_minor')->nullable()->comment('Fixed required deposit in currency minor units when deposit_type is fixed.');
            $table->unsignedSmallInteger('deposit_rate_bps')->nullable()->comment('Required-deposit percentage in basis points when deposit_type is percentage.');
            $table->boolean('is_refundable')->default(true)->comment('Whether cancellation may qualify for a refund under the rate terms.');
            $table->unsignedInteger('free_cancel_before_minutes')->nullable()->comment('Minutes before arrival until which free cancellation is permitted.');
            $table->text('cancellation_terms')->nullable()->comment('Guest-facing rate-specific cancellation conditions.');
            $table->boolean('is_public')->default(true)->comment('Whether eligible storefront searches may return this rate.');
            $table->unsignedInteger('sort_order')->default(0)->comment('Ascending display priority among rates for the unit type.');
            $table->timestamp('published_at')->nullable()->comment('UTC timestamp when the rate became publicly eligible.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the rate plan was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the rate plan was last changed.');
            $table->softDeletes()->comment('Timestamp when the rate plan was archived from ordinary queries.');

            $table->unique(['unit_type_id', 'code'], 'pb_rate_plans_unit_code_unique');
            $table->index(['property_id', 'unit_type_id', 'status', 'is_public'], 'pb_rate_plans_search_index');
            $table->index(['pricing_unit', 'status'], 'pb_rate_plans_pricing_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_rate_plans');
    }
};
