<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates receptionist-owned shifts and cash reconciliation snapshots. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_shifts', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for POB transaction relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('property_id')->comment('Property operated during this reception shift.')->constrained('property_booking_properties')->restrictOnDelete();
            $table->foreignId('register_id')->comment('Reception register operated during this shift.')->constrained('property_booking_registers')->restrictOnDelete();
            $table->foreignId('receptionist_id')->comment('Operator responsible for terminal activity during this shift.')->constrained('users')->restrictOnDelete();
            $table->unsignedBigInteger('register_open_guard')->nullable()->unique()->comment('Register ID while open and null when closed, enforcing one open shift per register.');
            $table->unsignedBigInteger('receptionist_open_guard')->nullable()->unique()->comment('Receptionist ID while open and null when closed, enforcing one open shift per operator.');
            $table->string('status', 20)->default('open')->comment('Lifecycle backed by PointOfBooking Enums ReceptionShiftStatus.');
            $table->char('currency', 3)->comment('ISO 4217 currency copied from the property when the shift opens.');
            $table->unsignedBigInteger('opening_float_minor')->default(0)->comment('Cash placed at the register when the shift opens, in currency minor units.');
            $table->unsignedBigInteger('expected_cash_minor')->default(0)->comment('Opening float plus net completed cash payments, in currency minor units.');
            $table->unsignedBigInteger('counted_cash_minor')->nullable()->comment('Physical cash counted during shift close, in currency minor units.');
            $table->bigInteger('variance_minor')->nullable()->comment('Signed counted-minus-expected cash difference, in currency minor units.');
            $table->text('opening_note')->nullable()->comment('Optional operational note recorded at shift opening.');
            $table->text('closing_note')->nullable()->comment('Optional reconciliation explanation recorded at shift closing.');
            $table->foreignId('opened_by')->comment('Authorized user who opened the shift.')->constrained('users')->restrictOnDelete();
            $table->timestamp('opened_at')->comment('UTC timestamp when the shift became available for POB transactions.');
            $table->foreignId('closed_by')->nullable()->comment('Authorized user who completed reconciliation.')->constrained('users')->nullOnDelete();
            $table->timestamp('closed_at')->nullable()->comment('UTC timestamp when the shift was reconciled and closed.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the shift record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the shift record was last changed.');

            $table->index(['property_id', 'status', 'opened_at'], 'pb_shifts_property_status_index');
            $table->index(['register_id', 'status'], 'pb_shifts_register_status_index');
            $table->index(['receptionist_id', 'status'], 'pb_shifts_receptionist_status_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_shifts');
    }
};
