<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates one immutable unit-type and rate snapshot per reserved unit. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_stays', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for allocation and occupant relationships.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('booking_id')->comment('Booking aggregate that owns this reserved unit line.')->constrained('property_bookings')->cascadeOnDelete();
            $table->foreignId('unit_type_id')->nullable()->comment('Optional current unit-type reference; snapshots preserve historical meaning.')->constrained('property_booking_unit_types')->nullOnDelete();
            $table->foreignId('rate_plan_id')->nullable()->comment('Optional current rate-plan reference; snapshots preserve historical meaning.')->constrained('property_booking_rate_plans')->nullOnDelete();
            $table->unsignedSmallInteger('line_number')->comment('Stable line sequence unique within the booking.');
            $table->timestamp('starts_at')->comment('Inclusive UTC stay start matching the booking interval in version one.');
            $table->timestamp('ends_at')->comment('Exclusive UTC stay end matching the booking interval in version one.');
            $table->string('pricing_unit', 20)->comment('Billing basis snapshotted from Pricing Enums StayPricingUnit.');
            $table->unsignedSmallInteger('billable_units')->comment('Whole hours, day-use periods, or nights charged for this stay.');
            $table->unsignedSmallInteger('adult_count')->default(1)->comment('Adult occupants assigned to this stay line.');
            $table->unsignedSmallInteger('child_count')->default(0)->comment('Child occupants assigned to this stay line.');
            $table->unsignedSmallInteger('infant_count')->default(0)->comment('Infant occupants assigned to this stay line.');
            $table->string('unit_type_name', 180)->comment('Immutable sellable unit-type name snapshot.');
            $table->string('unit_type_code', 40)->comment('Immutable unit-type code snapshot.');
            $table->string('rate_plan_name', 160)->comment('Immutable rate-plan name snapshot.');
            $table->string('rate_plan_code', 40)->comment('Immutable rate-plan code snapshot.');
            $table->unsignedBigInteger('unit_rate_minor')->comment('Resolved base rate for one billing unit in currency minor units.');
            $table->unsignedBigInteger('extra_guest_minor')->default(0)->comment('Total extra-occupant surcharge across billable units in currency minor units.');
            $table->unsignedBigInteger('subtotal_minor')->comment('Accommodation subtotal before line discount and tax treatment.');
            $table->unsignedBigInteger('discount_minor')->default(0)->comment('Discount allocated to this stay line in currency minor units.');
            $table->unsignedSmallInteger('tax_rate_bps')->default(0)->comment('Tax rate snapshot in basis points.');
            $table->unsignedBigInteger('tax_minor')->default(0)->comment('Tax attributable to this stay line in currency minor units.');
            $table->unsignedBigInteger('total_minor')->comment('Final stay line amount in currency minor units.');
            $table->boolean('is_tax_inclusive')->default(true)->comment('Whether snapshotted rate amounts include tax.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the stay snapshot was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when an authorized repricing operation last replaced the snapshot.');

            $table->unique(['booking_id', 'line_number'], 'pb_stays_booking_line_unique');
            $table->index(['unit_type_id', 'starts_at', 'ends_at'], 'pb_stays_unit_type_interval_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_stays');
    }
};
