<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates auditable operational blocks over half-open UTC intervals. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_availability_blocks', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key used for availability locking.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('property_id')->comment('Property owning the blocked concrete unit.')->constrained('property_booking_properties')->cascadeOnDelete();
            $table->foreignId('unit_id')->comment('Concrete unit removed from inventory for the interval.')->constrained('property_booking_units')->cascadeOnDelete();
            $table->foreignId('created_by')->comment('Authorized user who created the block.')->constrained('users')->restrictOnDelete();
            $table->foreignId('released_by')->nullable()->comment('Authorized user who released the block.')->constrained('users')->nullOnDelete();
            $table->string('type', 30)->comment('Block reason category backed by Availability Enums AvailabilityBlockType.');
            $table->string('status', 20)->default('active')->comment('Lifecycle backed by Availability Enums AvailabilityBlockStatus.');
            $table->timestamp('starts_at')->comment('Inclusive UTC instant at which the unit becomes unavailable.');
            $table->timestamp('ends_at')->comment('Exclusive UTC instant at which the unit becomes available, before turnover rules.');
            $table->string('reason', 255)->comment('Required bounded staff-readable reason for removing availability.');
            $table->text('internal_note')->nullable()->comment('Optional staff-only detail never rendered publicly.');
            $table->timestamp('released_at')->nullable()->comment('UTC timestamp when the block stopped consuming availability.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the block was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the block was last changed.');

            $table->index(['unit_id', 'status', 'starts_at', 'ends_at'], 'pb_blocks_unit_interval_index');
            $table->index(['property_id', 'status', 'starts_at'], 'pb_blocks_property_calendar_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_availability_blocks');
    }
};
