<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates authoritative exact-unit allocations over half-open intervals. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_unit_assignments', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for allocation lifecycle operations.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('property_id')->comment('Property owning the allocated unit and booking.')->constrained('property_booking_properties')->restrictOnDelete();
            $table->foreignId('booking_id')->comment('Booking aggregate consuming this availability.')->constrained('property_bookings')->cascadeOnDelete();
            $table->foreignId('booking_stay_id')->comment('Single booking stay satisfied by this exact unit.')->constrained('property_booking_stays')->cascadeOnDelete();
            $table->foreignId('unit_id')->comment('Concrete physical unit allocated to the stay.')->constrained('property_booking_units')->restrictOnDelete();
            $table->string('status', 20)->default('active')->comment('Lifecycle backed by Bookings Enums UnitAssignmentStatus.');
            $table->timestamp('starts_at')->comment('Inclusive UTC instant at which the assignment consumes availability.');
            $table->timestamp('ends_at')->comment('Exclusive UTC instant at which the stay ends before turnover buffer.');
            $table->unsignedBigInteger('active_stay_guard')->nullable()->unique()->comment('Stay ID while active and null after release, enforcing one active unit per stay.');
            $table->foreignId('assigned_by')->nullable()->comment('Staff allocator, null for a public automatic allocation.')->constrained('users')->nullOnDelete();
            $table->timestamp('assigned_at')->comment('UTC timestamp when allocation committed.');
            $table->foreignId('released_by')->nullable()->comment('Authorized user who released or moved the allocation.')->constrained('users')->nullOnDelete();
            $table->timestamp('released_at')->nullable()->comment('UTC timestamp when the assignment stopped consuming availability.');
            $table->string('release_reason', 255)->nullable()->comment('Required operational reason for a manual release or move.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the assignment was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the assignment lifecycle last changed.');

            $table->index(['unit_id', 'status', 'starts_at', 'ends_at'], 'pb_assignments_unit_interval_index');
            $table->index(['booking_id', 'status'], 'pb_assignments_booking_index');
            $table->index(['booking_stay_id', 'status'], 'pb_assignments_stay_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_unit_assignments');
    }
};
