<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Creates manual and adapter-ready booking tender records. */
return new class extends Migration
{
    /** Create the documented module table and constraints. */
    public function up(): void
    {
        Schema::create('property_booking_payments', function (Blueprint $table): void {
            $table->id()->comment('Internal integer primary key for payment lifecycle operations.');
            $table->ulid('ulid')->unique()->comment('Immutable public route identifier generated by the module HasUlid concern.');
            $table->foreignId('booking_id')->comment('Booking aggregate receiving this tender.')->constrained('property_bookings')->cascadeOnDelete();
            $table->foreignId('reception_shift_id')->nullable()->comment('Reception shift responsible for an in-person tender.')->constrained('property_booking_shifts')->nullOnDelete();
            $table->foreignId('recorded_by')->comment('Authorized user who recorded the tender or gateway result.')->constrained('users')->restrictOnDelete();
            $table->string('method', 30)->comment('Tender type backed by Bookings Enums BookingPaymentMethod.');
            $table->string('status', 20)->default('pending')->comment('Tender lifecycle backed by Bookings Enums BookingPaymentRecordStatus.');
            $table->char('currency', 3)->comment('ISO 4217 currency that must match the booking.');
            $table->unsignedBigInteger('amount_minor')->comment('Payment value applied to the booking in currency minor units.');
            $table->unsignedBigInteger('tendered_minor')->nullable()->comment('Physical cash offered before change; null for non-cash tenders.');
            $table->unsignedBigInteger('change_minor')->default(0)->comment('Cash returned to the guest and excluded from booking settlement.');
            $table->unsignedBigInteger('refunded_amount_minor')->default(0)->comment('Amount returned through the explicit full-refund lifecycle.');
            $table->string('reference', 160)->nullable()->comment('Sanitized external or manual reference without account, card, or provider secrets.');
            $table->json('metadata')->nullable()->comment('Sanitized non-sensitive adapter context; raw gateway payloads are prohibited.');
            $table->timestamp('paid_at')->nullable()->comment('UTC timestamp when the tender completed successfully.');
            $table->timestamp('failed_at')->nullable()->comment('UTC timestamp when the tender entered failed state.');
            $table->timestamp('refunded_at')->nullable()->comment('UTC timestamp when the completed amount was fully refunded.');
            $table->timestamp('created_at')->nullable()->comment('Timestamp when the payment record was created.');
            $table->timestamp('updated_at')->nullable()->comment('Timestamp when the payment lifecycle last changed.');

            $table->index(['booking_id', 'status'], 'pb_payments_booking_status_index');
            $table->index(['reception_shift_id', 'status'], 'pb_payments_shift_status_index');
            $table->index(['method', 'reference'], 'pb_payments_method_reference_index');
            $table->index('paid_at', 'pb_payments_paid_at_index');
        });
    }

    /** Remove the module table during rollback. */
    public function down(): void
    {
        Schema::dropIfExists('property_booking_payments');
    }
};
